#!/usr/bin/env bash
set -euo pipefail

gloat_src=${1:?gloat.clj path required}
tmp="$gloat_src.tmp.$$"

perl -0pe '
  my $old = qr{    \(when-let \[extra-go-dir \(System/getenv "GLOAT_EXTRA_GO_DIR"\)\]\n      \(when \(fs/exists\? extra-go-dir\)\n        \(doseq \[file \(fs/glob extra-go-dir "\*\*/\*"\)\]\n          \(when \(fs/regular-file\? file\)\n            \(let \[rel-path \(str \(fs/relativize extra-go-dir file\)\)\n                  target \(str output-dir "/internal/goyamlparser/" rel-path\)\]\n              \(fs/create-dirs \(fs/parent target\)\)\n              \(fs/copy file target \{:replace-existing true\}\)\)\)\)\)\)};
  my $new = q{    (when-let [extra-go-dir (System/getenv "GLOAT_EXTRA_GO_DIR")]
      (when (fs/exists? extra-go-dir)
        (let [target (str output-dir "/internal/goyamlparser")]
          (fs/delete-tree target)
          (fs/create-dirs (fs/parent target))
          (process/shell "cp" "-R" extra-go-dir target))))};

  if (!s/$old/$new/) {
    my $needle = quotemeta(q{    (fs/create-dirs output-dir)});
    $new = q{    (fs/create-dirs output-dir)
    (when-let [extra-go-dir (System/getenv "GLOAT_EXTRA_GO_DIR")]
      (when (fs/exists? extra-go-dir)
        (let [target (str output-dir "/internal/goyamlparser")]
          (fs/delete-tree target)
          (fs/create-dirs (fs/parent target))
          (process/shell "cp" "-R" extra-go-dir target))))};
    s/$needle/$new/ or die "patch target not found\n";
  }
' "$gloat_src" > "$tmp"

mv "$tmp" "$gloat_src"
