// Code generated by glojure codegen. DO NOT EDIT.

package representer

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/representer", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.representer"
func LoadNS() {
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_coll_QMARK_ := lang.NewSymbolUnchecked("coll?")
	sym_ex_DASH_info := lang.NewSymbolUnchecked("ex-info")
	sym_false_QMARK_ := lang.NewSymbolUnchecked("false?")
	sym_integer_QMARK_ := lang.NewSymbolUnchecked("integer?")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_map_QMARK_ := lang.NewSymbolUnchecked("map?")
	sym_mapv := lang.NewSymbolUnchecked("mapv")
	sym_number_QMARK_ := lang.NewSymbolUnchecked("number?")
	sym_represent := lang.NewSymbolUnchecked("represent")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_subs := lang.NewSymbolUnchecked("subs")
	sym_true_QMARK_ := lang.NewSymbolUnchecked("true?")
	sym_type := lang.NewSymbolUnchecked("type")
	sym_value := lang.NewSymbolUnchecked("value")
	sym_yamlstar_DOT_representer := lang.NewSymbolUnchecked("yamlstar.representer")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_kind := lang.NewKeyword("kind")
	kw_line := lang.NewKeyword("line")
	kw_mapping := lang.NewKeyword("mapping")
	kw_ns := lang.NewKeyword("ns")
	kw_scalar := lang.NewKeyword("scalar")
	kw_sequence := lang.NewKeyword("sequence")
	kw_tag := lang.NewKeyword("tag")
	kw_type := lang.NewKeyword("type")
	kw_value := lang.NewKeyword("value")
	// var clojure.core/coll?
	var_clojure_DOT_core_coll_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_coll_QMARK_)
	// var clojure.core/ex-info
	var_clojure_DOT_core_ex_DASH_info := lang.InternVarName(sym_clojure_DOT_core, sym_ex_DASH_info)
	// var clojure.core/false?
	var_clojure_DOT_core_false_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_false_QMARK_)
	// var clojure.core/integer?
	var_clojure_DOT_core_integer_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_integer_QMARK_)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/map?
	var_clojure_DOT_core_map_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_map_QMARK_)
	// var clojure.core/mapv
	var_clojure_DOT_core_mapv := lang.InternVarName(sym_clojure_DOT_core, sym_mapv)
	// var clojure.core/number?
	var_clojure_DOT_core_number_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_number_QMARK_)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/subs
	var_clojure_DOT_core_subs := lang.InternVarName(sym_clojure_DOT_core, sym_subs)
	// var clojure.core/true?
	var_clojure_DOT_core_true_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_true_QMARK_)
	// var clojure.core/type
	var_clojure_DOT_core_type := lang.InternVarName(sym_clojure_DOT_core, sym_type)
	// var yamlstar.representer/represent
	var_yamlstar_DOT_representer_represent := lang.InternVarName(sym_yamlstar_DOT_representer, sym_represent)
	aotExternalFn0 := aotLinkFn1(var_clojure_DOT_core_true_QMARK_)
	aotExternalFn1 := aotLinkFn1(var_clojure_DOT_core_false_QMARK_)
	aotExternalFn11 := aotLinkFn1(var_clojure_DOT_core_coll_QMARK_)
	aotExternalFn12 := aotLinkFn2(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn13 := aotLinkFn1(var_clojure_DOT_core_type)
	aotExternalFn2 := aotLinkFn1(var_clojure_DOT_core_number_QMARK_)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_integer_QMARK_)
	aotExternalFn4 := aotLinkFn1(var_clojure_DOT_core_str)
	aotExternalFn5 := aotLinkFn1(var_clojure_DOT_core_keyword_QMARK_)
	aotExternalFn6 := aotLinkFn2(var_clojure_DOT_core_subs)
	aotExternalFn7 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	aotExternalFn8 := aotLinkFn1(var_clojure_DOT_core_map_QMARK_)
	aotExternalFn9 := aotLinkFn2(var_clojure_DOT_core_mapv)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_representer)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// represent
	{
		tmp0 := sym_represent
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := lang.Identical(v2, nil)
			if lang.IsTruthy(tmp4) {
				tmp5 := lang.NewMap(kw_kind, kw_scalar, kw_tag, "!!null", kw_value, "null")
				tmp3 = tmp5
			} else {
				var tmp6 any
				tmp7 := aotExternalFn0(v2)
				if lang.IsTruthy(tmp7) {
					tmp8 := lang.NewMap(kw_kind, kw_scalar, kw_tag, "!!bool", kw_value, "true")
					tmp6 = tmp8
				} else {
					var tmp9 any
					tmp10 := aotExternalFn1(v2)
					if lang.IsTruthy(tmp10) {
						tmp11 := lang.NewMap(kw_kind, kw_scalar, kw_tag, "!!bool", kw_value, "false")
						tmp9 = tmp11
					} else {
						var tmp12 any
						tmp13 := aotExternalFn2(v2)
						if lang.IsTruthy(tmp13) {
							var tmp14 any
							tmp15 := aotExternalFn3(v2)
							if lang.IsTruthy(tmp15) {
								tmp14 = "!!int"
							} else {
								tmp14 = "!!float"
							}
							tmp16 := aotExternalFn4(v2)
							tmp17 := lang.NewMap(kw_kind, kw_scalar, kw_tag, tmp14, kw_value, tmp16)
							tmp12 = tmp17
						} else {
							var tmp18 any
							tmp19 := aotExternalFn5(v2)
							if lang.IsTruthy(tmp19) {
								tmp20 := aotExternalFn4(v2)
								tmp21 := aotExternalFn6(tmp20, int64(1))
								tmp22 := lang.NewMap(kw_kind, kw_scalar, kw_tag, "!!str", kw_value, tmp21)
								tmp18 = tmp22
							} else {
								var tmp23 any
								tmp24 := aotExternalFn7(v2)
								if lang.IsTruthy(tmp24) {
									tmp25 := lang.NewMap(kw_kind, kw_scalar, kw_tag, "!!str", kw_value, v2)
									tmp23 = tmp25
								} else {
									var tmp26 any
									tmp27 := aotExternalFn8(v2)
									if lang.IsTruthy(tmp27) {
										var tmp28 lang.FnFunc1
										tmp28 = lang.FnFunc1(func(p0 any) any {
											v29 := p0
											_ = v29
											var tmp30 any
											{ // let
												// let binding "vec__2"
												var v31 any = v29
												_ = v31
												// let binding "k"
												tmp32 := runtime.RT.NthDefault(v31, lang.IntCast(int64(0)), nil)
												var v33 any = tmp32
												_ = v33
												// let binding "v"
												tmp34 := runtime.RT.NthDefault(v31, lang.IntCast(int64(1)), nil)
												var v35 any = tmp34
												_ = v35
												tmp36 := aotDirectFn0(v33)
												tmp37 := aotDirectFn0(v35)
												tmp38 := lang.NewVector(tmp36, tmp37)
												tmp30 = tmp38
											} // end let
											return tmp30
										})
										tmp29 := aotExternalFn9(tmp28, v2)
										tmp30 := lang.NewMap(kw_kind, kw_mapping, kw_tag, "!!map", kw_value, tmp29)
										tmp26 = tmp30
									} else {
										var tmp31 any
										tmp32 := aotExternalFn11(v2)
										if lang.IsTruthy(tmp32) {
											tmp33 := checkDerefVar(var_yamlstar_DOT_representer_represent)
											tmp34 := aotExternalFn9(tmp33, v2)
											tmp35 := lang.NewMap(kw_kind, kw_sequence, kw_tag, "!!seq", kw_value, tmp34)
											tmp31 = tmp35
										} else {
											tmp36 := aotExternalFn13(v2)
											tmp37 := lang.NewMap(kw_value, v2, kw_type, tmp36)
											tmp38 := aotExternalFn12("YAMLStar dump does not support this value", tmp37)
											panic(tmp38)
										}
										tmp26 = tmp31
									}
									tmp23 = tmp26
								}
								tmp18 = tmp23
							}
							tmp12 = tmp18
						}
						tmp9 = tmp12
					}
					tmp6 = tmp9
				}
				tmp3 = tmp6
			}
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_representer_represent = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_representer_represent.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/representer.glj", kw_line, int(5), kw_column, int(7), kw_end_DASH_line, int(5), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_value)), kw_doc, "Represent a native value as a YAMLStar node tree.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_representer))
		})
	}
}
