// Code generated by glojure codegen. DO NOT EDIT.

package shared_DASH_host

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	pluginloader4 "github.com/yaml/yamlstar/internal/goyamlparser/pluginloader"
	reflect "reflect"
	atomic "sync/atomic"
)

var aotDirectFn0 lang.FnFunc0
var aotDirectFn1 lang.FnFunc3
var aotDirectFn2 lang.FnFunc4
var aotDirectFn3 lang.FnFunc0

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var linked atomic.Pointer[lang.FnFunc1]
	return func(p0 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0)
		}
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		fn := aotLinkBoundFn1(vr)
		linked.Store(&fn)
		return fn(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn1(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var linked atomic.Pointer[lang.FnFunc2]
	return func(p0 any, p1 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1)
		}
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		fn := aotLinkBoundFn2(vr)
		linked.Store(&fn)
		return fn(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn2(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var linked atomic.Pointer[lang.FnFunc3]
	return func(p0 any, p1 any, p2 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2)
		}
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		fn := aotLinkBoundFn3(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn3(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/plugin/shared_host", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.plugin.shared-host"
func LoadNS() {
	sym_api := lang.NewSymbolUnchecked("api")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_input := lang.NewSymbolUnchecked("input")
	sym_install_BANG_ := lang.NewSymbolUnchecked("install!")
	sym_install_QMARK_ := lang.NewSymbolUnchecked("install?")
	sym_make_DASH_loader := lang.NewSymbolUnchecked("make-loader")
	sym_manifest := lang.NewSymbolUnchecked("manifest")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_options := lang.NewSymbolUnchecked("options")
	sym_parse := lang.NewSymbolUnchecked("parse")
	sym_plugin := lang.NewSymbolUnchecked("plugin")
	sym_require_DASH_glojure_DASH_runtime := lang.NewSymbolUnchecked("require-glojure-runtime")
	sym_set_DASH_event_DASH_source_DASH_loader_BANG_ := lang.NewSymbolUnchecked("set-event-source-loader!")
	sym_shared := lang.NewSymbolUnchecked("shared")
	sym_yamlstar_DOT_plugin := lang.NewSymbolUnchecked("yamlstar.plugin")
	sym_yamlstar_DOT_plugin_DOT_shared := lang.NewSymbolUnchecked("yamlstar.plugin.shared")
	sym_yamlstar_DOT_plugin_DOT_shared_DASH_host := lang.NewSymbolUnchecked("yamlstar.plugin.shared-host")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	// var yamlstar.plugin.shared-host/install!
	var_yamlstar_DOT_plugin_DOT_shared_DASH_host_install_BANG_ := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host, sym_install_BANG_)
	// var yamlstar.plugin.shared-host/manifest
	var_yamlstar_DOT_plugin_DOT_shared_DASH_host_manifest := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host, sym_manifest)
	// var yamlstar.plugin.shared-host/parse
	var_yamlstar_DOT_plugin_DOT_shared_DASH_host_parse := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host, sym_parse)
	// var yamlstar.plugin.shared-host/require-glojure-runtime
	var_yamlstar_DOT_plugin_DOT_shared_DASH_host_require_DASH_glojure_DASH_runtime := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host, sym_require_DASH_glojure_DASH_runtime)
	// var yamlstar.plugin.shared/make-loader
	var_yamlstar_DOT_plugin_DOT_shared_make_DASH_loader := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_make_DASH_loader)
	// var yamlstar.plugin/set-event-source-loader!
	var_yamlstar_DOT_plugin_set_DASH_event_DASH_source_DASH_loader_BANG_ := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_set_DASH_event_DASH_source_DASH_loader_BANG_)
	aotExternalFn0 := aotLinkFn1(var_yamlstar_DOT_plugin_set_DASH_event_DASH_source_DASH_loader_BANG_)
	aotExternalFn1 := aotLinkFn2(var_yamlstar_DOT_plugin_DOT_shared_make_DASH_loader)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_plugin, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin))
	ns.AddAlias(sym_shared, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
	// manifest
	{
		tmp0 := sym_manifest
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			tmp5 := aotDirectFn3()
			_ = tmp5
			var tmp6 any
			{ // let
				// let binding "vec__29"
				tmp7 := lang.Apply3(pluginloader4.Manifest, v2, v3, v4)
				var v8 any = tmp7
				_ = v8
				// let binding "text"
				tmp9 := runtime.RT.NthDefault(v8, lang.IntCast(int64(0)), nil)
				var v10 any = tmp9
				_ = v10
				// let binding "error"
				tmp11 := runtime.RT.NthDefault(v8, lang.IntCast(int64(1)), nil)
				var v12 any = tmp11
				_ = v12
				var tmp13 any
				tmp14 := lang.Identical(v12, nil)
				if lang.IsTruthy(tmp14) {
					tmp13 = v10
				} else {
					panic(v12)
				}
				tmp6 = tmp13
			} // end let
			return tmp6
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_manifest = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_manifest.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared_host.glj", kw_line, int(13), kw_column, int(8), kw_end_DASH_line, int(13), kw_end_DASH_column, int(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_api, sym_name, sym_install_QMARK_)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host))
		}, false)
	}
	// parse
	{
		tmp0 := sym_parse
		var tmp1 lang.FnFunc4
		tmp1 = lang.FnFunc4(func(p0, p1, p2, p3 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			v5 := p3
			_ = v5
			tmp6 := aotDirectFn3()
			_ = tmp6
			var tmp7 any
			{ // let
				// let binding "vec__32"
				tmp8 := lang.Apply4(pluginloader4.Parse, v2, v3, v4, v5)
				var v9 any = tmp8
				_ = v9
				// let binding "text"
				tmp10 := runtime.RT.NthDefault(v9, lang.IntCast(int64(0)), nil)
				var v11 any = tmp10
				_ = v11
				// let binding "status"
				tmp12 := runtime.RT.NthDefault(v9, lang.IntCast(int64(1)), nil)
				var v13 any = tmp12
				_ = v13
				// let binding "error"
				tmp14 := runtime.RT.NthDefault(v9, lang.IntCast(int64(2)), nil)
				var v15 any = tmp14
				_ = v15
				var tmp16 any
				tmp17 := lang.Identical(v15, nil)
				if lang.IsTruthy(tmp17) {
					tmp18 := lang.NewVector(v13, v11)
					tmp16 = tmp18
				} else {
					panic(v15)
				}
				tmp7 = tmp16
			} // end let
			return tmp7
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_parse = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_parse.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared_host.glj", kw_line, int(23), kw_column, int(8), kw_end_DASH_line, int(23), kw_end_DASH_column, int(12), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_api, sym_name, sym_input, sym_options)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host))
		}, false)
	}
	// require-glojure-runtime
	{
		tmp0 := sym_require_DASH_glojure_DASH_runtime
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			return nil
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_require_DASH_glojure_DASH_runtime = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_require_DASH_glojure_DASH_runtime.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared_host.glj", kw_line, int(6), kw_column, int(8), kw_end_DASH_line, int(6), kw_end_DASH_column, int(30), kw_private, true, kw_arglists, lang.NewList(lang.NewVector()), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host))
		}, false)
	}
	// install!
	{
		tmp0 := sym_install_BANG_
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn3()
			_ = tmp2
			tmp3 := checkDerefVar(var_yamlstar_DOT_plugin_DOT_shared_DASH_host_manifest)
			tmp4 := checkDerefVar(var_yamlstar_DOT_plugin_DOT_shared_DASH_host_parse)
			tmp5 := aotExternalFn1(tmp3, tmp4)
			tmp6 := aotExternalFn0(tmp5)
			return tmp6
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_install_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_DASH_host_install_BANG_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared_host.glj", kw_line, int(35), kw_column, int(7), kw_end_DASH_line, int(35), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Install the Glojure shared-library event-source loader.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared_DASH_host))
		}, false)
	}
}
