// Code generated by glojure codegen. DO NOT EDIT.

package resolver

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	regexp4 "regexp"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc1
var aotDirectFn3 lang.FnFunc1

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/resolver", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.resolver"
func LoadNS() {
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_infer_DASH_scalar_DASH_tag := lang.NewSymbolUnchecked("infer-scalar-tag")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_mapv := lang.NewSymbolUnchecked("mapv")
	sym_node := lang.NewSymbolUnchecked("node")
	sym_nodes := lang.NewSymbolUnchecked("nodes")
	sym_re_DASH_matches := lang.NewSymbolUnchecked("re-matches")
	sym_resolve := lang.NewSymbolUnchecked("resolve")
	sym_resolve_DASH_all := lang.NewSymbolUnchecked("resolve-all")
	sym_resolve_DASH_node := lang.NewSymbolUnchecked("resolve-node")
	sym_value := lang.NewSymbolUnchecked("value")
	sym_yamlstar_DOT_resolver := lang.NewSymbolUnchecked("yamlstar.resolver")
	kw_alias := lang.NewKeyword("alias")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_kind := lang.NewKeyword("kind")
	kw_line := lang.NewKeyword("line")
	kw_mapping := lang.NewKeyword("mapping")
	kw_ns := lang.NewKeyword("ns")
	kw_scalar := lang.NewKeyword("scalar")
	kw_sequence := lang.NewKeyword("sequence")
	kw_style := lang.NewKeyword("style")
	kw_tag := lang.NewKeyword("tag")
	kw_value := lang.NewKeyword("value")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/mapv
	var_clojure_DOT_core_mapv := lang.InternVarName(sym_clojure_DOT_core, sym_mapv)
	// var clojure.core/re-matches
	var_clojure_DOT_core_re_DASH_matches := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_matches)
	// var yamlstar.resolver/infer-scalar-tag
	var_yamlstar_DOT_resolver_infer_DASH_scalar_DASH_tag := lang.InternVarName(sym_yamlstar_DOT_resolver, sym_infer_DASH_scalar_DASH_tag)
	// var yamlstar.resolver/resolve
	var_yamlstar_DOT_resolver_resolve := lang.InternVarName(sym_yamlstar_DOT_resolver, sym_resolve)
	// var yamlstar.resolver/resolve-all
	var_yamlstar_DOT_resolver_resolve_DASH_all := lang.InternVarName(sym_yamlstar_DOT_resolver, sym_resolve_DASH_all)
	// var yamlstar.resolver/resolve-node
	var_yamlstar_DOT_resolver_resolve_DASH_node := lang.InternVarName(sym_yamlstar_DOT_resolver, sym_resolve_DASH_node)
	aotExternalFn0 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn1 := aotLinkFn2(var_clojure_DOT_core_re_DASH_matches)
	aotExternalFn2 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn3 := aotLinkFn2(var_clojure_DOT_core_mapv)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_resolver)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"resolve",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	var closed0 any
	var closed1 any
	var closed2 any
	var closed3 any
	var closed4 any
	var closed5 any
	{
		closed0 = regexp4.MustCompile("null|Null|NULL|~")
	}
	{
		closed1 = regexp4.MustCompile("true|True|TRUE|false|False|FALSE")
	}
	{
		closed2 = regexp4.MustCompile("[-+]?[0-9]+")
	}
	{
		closed3 = regexp4.MustCompile("[-+]?(\\.[0-9]+|[0-9]+(\\.[0-9]*)?)([eE][-+]?[0-9]+)?")
	}
	{
		closed4 = regexp4.MustCompile("[+-]?(\\.inf|\\.Inf|\\.INF)")
	}
	{
		closed5 = regexp4.MustCompile("\\.nan|\\.NaN|\\.NAN")
	}
	// infer-scalar-tag
	{
		tmp0 := sym_infer_DASH_scalar_DASH_tag
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			var tmp4 any
			{ // let
				// let binding "or__0__auto__"
				tmp5 := aotExternalFn0(v2, "")
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					tmp7 = v6
				} else {
					tmp8 := aotExternalFn1(closed0, v2)
					tmp7 = tmp8
				}
				tmp4 = tmp7
			} // end let
			if lang.IsTruthy(tmp4) {
				tmp3 = "!!null"
			} else {
				var tmp5 any
				tmp6 := aotExternalFn1(closed1, v2)
				if lang.IsTruthy(tmp6) {
					tmp5 = "!!bool"
				} else {
					var tmp7 any
					tmp8 := aotExternalFn1(closed2, v2)
					if lang.IsTruthy(tmp8) {
						tmp7 = "!!int"
					} else {
						var tmp9 any
						var tmp10 any
						{ // let
							// let binding "or__0__auto__"
							tmp11 := aotExternalFn1(closed3, v2)
							var v12 any = tmp11
							_ = v12
							var tmp13 any
							if lang.IsTruthy(v12) {
								tmp13 = v12
							} else {
								var tmp14 any
								{ // let
									// let binding "or__0__auto__"
									tmp15 := aotExternalFn1(closed4, v2)
									var v16 any = tmp15
									_ = v16
									var tmp17 any
									if lang.IsTruthy(v16) {
										tmp17 = v16
									} else {
										tmp18 := aotExternalFn1(closed5, v2)
										tmp17 = tmp18
									}
									tmp14 = tmp17
								} // end let
								tmp13 = tmp14
							}
							tmp10 = tmp13
						} // end let
						if lang.IsTruthy(tmp10) {
							tmp9 = "!!float"
						} else {
							tmp9 = "!!str"
						}
						tmp7 = tmp9
					}
					tmp5 = tmp7
				}
				tmp3 = tmp5
			}
			return tmp3
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_resolver_infer_DASH_scalar_DASH_tag = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_resolver_infer_DASH_scalar_DASH_tag.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/resolver.glj", kw_line, int(10), kw_column, int(7), kw_end_DASH_line, int(10), kw_end_DASH_column, int(22), kw_arglists, lang.NewList(lang.NewVector(sym_value)), kw_doc, "Infer the tag for an untagged scalar based on YAML 1.2 core schema.\n\n  Args:\n    value: The string value of the scalar\n\n  Returns:\n    A tag string (!!null, !!bool, !!int, !!float, or !!str)", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_resolver))
		})
	}
	// resolve
	{
		tmp0 := sym_resolve
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn3(v2)
			return tmp3
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_resolver_resolve = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_resolver_resolve.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/resolver.glj", kw_line, int(92), kw_column, int(7), kw_end_DASH_line, int(92), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_doc, "Resolve tags for a node tree.\n\n  Walks the entire tree and adds tags to all untagged nodes.\n\n  Args:\n    node: A node tree from composer\n\n  Returns:\n    The same node tree structure with all tags resolved", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_resolver))
		})
	}
	// resolve-node
	{
		tmp0 := sym_resolve_DASH_node
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			if lang.IsTruthy(v2) {
				var tmp4 any
				{ // let
					// let binding "G__40"
					tmp5 := kw_kind.Invoke1(v2)
					var v6 any = tmp5
					_ = v6
					// case
					var tmp7 any
					var tmp8 int64
					tmp8 = int64(uint32(lang.IdentityHash(v6)>>3) & uint32(3))
					// case entry 0 (key=0, collision=false)
					if tmp8 == 0 {
						if v6 == kw_alias {
							tmp7 = v2
						} else {
							tmp7 = v2
						}
						// case entry 1 (key=1, collision=false)
					} else if tmp8 == 1 {
						if v6 == kw_scalar {
							var tmp9 any
							{ // let
								// let binding "tag"
								var tmp10 any
								tmp11 := kw_tag.Invoke1(v2)
								tmp12 := aotExternalFn0("!", tmp11)
								if lang.IsTruthy(tmp12) {
									tmp10 = "!!str"
								} else {
									var tmp13 any
									tmp14 := kw_tag.Invoke1(v2)
									if lang.IsTruthy(tmp14) {
										tmp15 := kw_tag.Invoke1(v2)
										tmp13 = tmp15
									} else {
										var tmp16 any
										tmp17 := kw_style.Invoke1(v2)
										if lang.IsTruthy(tmp17) {
											tmp16 = "!!str"
										} else {
											tmp18 := kw_value.Invoke1(v2)
											tmp19 := aotDirectFn0(tmp18)
											tmp16 = tmp19
										}
										tmp13 = tmp16
									}
									tmp10 = tmp13
								}
								var v20 any = tmp10
								_ = v20
								var tmp21 any = v2
								tmp21 = lang.Assoc(tmp21, kw_tag, v20)
								tmp9 = tmp21
							} // end let
							tmp7 = tmp9
						} else {
							tmp7 = v2
						}
						// case entry 2 (key=2, collision=false)
					} else if tmp8 == 2 {
						if v6 == kw_mapping {
							var tmp10 any
							{ // let
								// let binding "tag"
								var tmp11 any
								tmp12 := kw_tag.Invoke1(v2)
								tmp13 := aotExternalFn0("!", tmp12)
								if lang.IsTruthy(tmp13) {
									tmp11 = "!!map"
								} else {
									var tmp14 any
									{ // let
										// let binding "or__0__auto__"
										tmp15 := kw_tag.Invoke1(v2)
										var v16 any = tmp15
										_ = v16
										var tmp17 any
										if lang.IsTruthy(v16) {
											tmp17 = v16
										} else {
											tmp17 = "!!map"
										}
										tmp14 = tmp17
									} // end let
									tmp11 = tmp14
								}
								var v15 any = tmp11
								_ = v15
								// let binding "pairs"
								tmp16 := kw_value.Invoke1(v2)
								var v17 any = tmp16
								_ = v17
								// let binding "resolved-pairs"
								var tmp18 lang.FnFunc1
								tmp18 = lang.FnFunc1(func(p0 any) any {
									v19 := p0
									_ = v19
									var tmp20 any
									{ // let
										// let binding "vec__42"
										var v21 any = v19
										_ = v21
										// let binding "k"
										tmp22 := runtime.RT.NthDefault(v21, lang.IntCast(int64(0)), nil)
										var v23 any = tmp22
										_ = v23
										// let binding "v"
										tmp24 := runtime.RT.NthDefault(v21, lang.IntCast(int64(1)), nil)
										var v25 any = tmp24
										_ = v25
										tmp26 := aotDirectFn3(v23)
										tmp27 := aotDirectFn3(v25)
										tmp28 := lang.NewVector(tmp26, tmp27)
										tmp20 = tmp28
									} // end let
									return tmp20
								})
								tmp19 := aotExternalFn3(tmp18, v17)
								var v20 any = tmp19
								_ = v20
								var tmp21 any = v2
								tmp21 = lang.Assoc(tmp21, kw_tag, v15)
								tmp21 = lang.Assoc(tmp21, kw_value, v20)
								tmp10 = tmp21
							} // end let
							tmp7 = tmp10
						} else {
							tmp7 = v2
						}
						// case entry 3 (key=3, collision=false)
					} else if tmp8 == 3 {
						if v6 == kw_sequence {
							var tmp11 any
							{ // let
								// let binding "tag"
								var tmp12 any
								tmp13 := kw_tag.Invoke1(v2)
								tmp14 := aotExternalFn0("!", tmp13)
								if lang.IsTruthy(tmp14) {
									tmp12 = "!!seq"
								} else {
									var tmp15 any
									{ // let
										// let binding "or__0__auto__"
										tmp16 := kw_tag.Invoke1(v2)
										var v17 any = tmp16
										_ = v17
										var tmp18 any
										if lang.IsTruthy(v17) {
											tmp18 = v17
										} else {
											tmp18 = "!!seq"
										}
										tmp15 = tmp18
									} // end let
									tmp12 = tmp15
								}
								var v16 any = tmp12
								_ = v16
								// let binding "items"
								tmp17 := kw_value.Invoke1(v2)
								var v18 any = tmp17
								_ = v18
								// let binding "resolved-items"
								tmp19 := checkDerefVar(var_yamlstar_DOT_resolver_resolve_DASH_node)
								tmp20 := aotExternalFn3(tmp19, v18)
								var v21 any = tmp20
								_ = v21
								var tmp22 any = v2
								tmp22 = lang.Assoc(tmp22, kw_tag, v16)
								tmp22 = lang.Assoc(tmp22, kw_value, v21)
								tmp11 = tmp22
							} // end let
							tmp7 = tmp11
						} else {
							tmp7 = v2
						}
					} else {
						tmp7 = v2
					}
					tmp4 = tmp7
				} // end let
				tmp3 = tmp4
			} else {
			}
			return tmp3
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_resolver_resolve_DASH_node = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_resolver_resolve_DASH_node.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/resolver.glj", kw_line, int(39), kw_column, int(7), kw_end_DASH_line, int(39), kw_end_DASH_column, int(18), kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_doc, "Add resolved tag to a node.\n\n  For untagged nodes, infers the tag based on YAML 1.2 core schema.\n  For the explicit non-specific tag (!), uses the kind-specific default tag.\n  For other already-tagged nodes, leaves the tag unchanged.\n  Recursively processes child nodes.\n\n  Args:\n    node: A node from the composer\n\n  Returns:\n    The node with :tag field populated", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_resolver))
		})
	}
	// resolve-all
	{
		tmp0 := sym_resolve_DASH_all
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := checkDerefVar(var_yamlstar_DOT_resolver_resolve_DASH_node)
			tmp4 := aotExternalFn2(tmp3, v2)
			return tmp4
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_resolver_resolve_DASH_all = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_resolver_resolve_DASH_all.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/resolver.glj", kw_line, int(105), kw_column, int(7), kw_end_DASH_line, int(105), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_nodes)), kw_doc, "Resolve tags for multiple node trees.\n\n  Args:\n    nodes: Sequence of node trees from composer\n\n  Returns:\n    Sequence of node trees with tags resolved", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_resolver))
		})
	}
}
