// Code generated by glojure codegen. DO NOT EDIT.

package prelude

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	os4 "os"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.ArityFn
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.ArityFn
var aotDirectFn3 lang.FnFunc1
var aotDirectFn4 lang.FnFunc1
var aotDirectFn5 lang.FnFunc1
var aotDirectFn6 lang.FnFunc1
var aotDirectFn7 lang.FnFunc1
var aotDirectFn8 lang.FnFunc1
var aotDirectFn9 lang.FnFunc1
var aotDirectFn10 lang.FnFunc1
var aotDirectFn11 lang.FnFunc1
var aotDirectFn12 lang.FnFunc1
var aotDirectFn13 lang.FnFunc1
var aotDirectFn14 lang.FnFunc1
var aotDirectFn15 lang.FnFunc1
var aotDirectFn16 lang.FnFunc3
var aotDirectFn17 lang.FnFunc1
var aotDirectFn18 lang.ArityFn
var aotDirectFn18Arity0 lang.FnFunc0
var aotDirectFn18Arity1 lang.FnFunc1
var aotDirectFn19 lang.FnFunc1
var aotDirectFn20 lang.FnFunc1

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func aotLinkFn4(vr *lang.Var) lang.FnFunc4 {
	if vr.IsBound() {
		return aotLinkBoundFn4(vr)
	}
	var once sync.Once
	var linked lang.FnFunc4
	return func(p0 any, p1 any, p2 any, p3 any) any {
		if !vr.IsBound() {
			return lang.Apply4(checkDerefVar(vr), p0, p1, p2, p3)
		}
		once.Do(func() { linked = aotLinkBoundFn4(vr) })
		return linked(p0, p1, p2, p3)
	}
}

func aotLinkBoundFn4(vr *lang.Var) lang.FnFunc4 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc4); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn4); ok {
		return fixed.Invoke4
	}
	return func(p0 any, p1 any, p2 any, p3 any) any { return lang.Apply4(fn, p0, p1, p2, p3) }
}

func init() {
	runtime.RegisterNSLoader("yaml_parser/prelude", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yaml-parser.prelude"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_DEBUG := lang.NewSymbolUnchecked("DEBUG")
	sym_FAIL := lang.NewSymbolUnchecked("FAIL")
	sym_GET_DASH_NAME_DASH_SENTINEL := lang.NewSymbolUnchecked("GET-NAME-SENTINEL")
	sym_args := lang.NewSymbolUnchecked("args")
	sym_chr := lang.NewSymbolUnchecked("chr")
	sym_chunk_DASH_first := lang.NewSymbolUnchecked("chunk-first")
	sym_chunk_DASH_rest := lang.NewSymbolUnchecked("chunk-rest")
	sym_chunked_DASH_seq_QMARK_ := lang.NewSymbolUnchecked("chunked-seq?")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_cp := lang.NewSymbolUnchecked("cp")
	sym_debug := lang.NewSymbolUnchecked("debug")
	sym_debug_DASH_rule := lang.NewSymbolUnchecked("debug-rule")
	sym_die := lang.NewSymbolUnchecked("die")
	sym_die_STAR_ := lang.NewSymbolUnchecked("die*")
	sym_env := lang.NewSymbolUnchecked("env")
	sym_ex_DASH_info := lang.NewSymbolUnchecked("ex-info")
	sym_f := lang.NewSymbolUnchecked("f")
	sym_false_QMARK_ := lang.NewSymbolUnchecked("false?")
	sym_fn_QMARK_ := lang.NewSymbolUnchecked("fn?")
	sym_from_DASH_code_DASH_point := lang.NewSymbolUnchecked("from-code-point")
	sym_func := lang.NewSymbolUnchecked("func")
	sym_func_DASH_name := lang.NewSymbolUnchecked("func-name")
	sym_hex_DASH_char := lang.NewSymbolUnchecked("hex-char")
	sym_is_DASH_array_QMARK_ := lang.NewSymbolUnchecked("is-array?")
	sym_is_DASH_boolean_QMARK_ := lang.NewSymbolUnchecked("is-boolean?")
	sym_is_DASH_function_QMARK_ := lang.NewSymbolUnchecked("is-function?")
	sym_is_DASH_null_QMARK_ := lang.NewSymbolUnchecked("is-null?")
	sym_is_DASH_number_QMARK_ := lang.NewSymbolUnchecked("is-number?")
	sym_is_DASH_object_QMARK_ := lang.NewSymbolUnchecked("is-object?")
	sym_is_DASH_string_QMARK_ := lang.NewSymbolUnchecked("is-string?")
	sym_join := lang.NewSymbolUnchecked("join")
	sym_key := lang.NewSymbolUnchecked("key")
	sym_keys := lang.NewSymbolUnchecked("keys")
	sym_keyword_QMARK_ := lang.NewSymbolUnchecked("keyword?")
	sym_map := lang.NewSymbolUnchecked("map")
	sym_map_QMARK_ := lang.NewSymbolUnchecked("map?")
	sym_msg := lang.NewSymbolUnchecked("msg")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_name_STAR_ := lang.NewSymbolUnchecked("name*")
	sym_not_DASH_empty := lang.NewSymbolUnchecked("not-empty")
	sym_number_QMARK_ := lang.NewSymbolUnchecked("number?")
	sym_o := lang.NewSymbolUnchecked("o")
	sym_pr_DASH_str := lang.NewSymbolUnchecked("pr-str")
	sym_prn := lang.NewSymbolUnchecked("prn")
	sym_seq_QMARK_ := lang.NewSymbolUnchecked("seq?")
	sym_start := lang.NewSymbolUnchecked("start")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_string_QMARK_ := lang.NewSymbolUnchecked("string?")
	sym_stringify := lang.NewSymbolUnchecked("stringify")
	sym_symbol_QMARK_ := lang.NewSymbolUnchecked("symbol?")
	sym_timer := lang.NewSymbolUnchecked("timer")
	sym_trace := lang.NewSymbolUnchecked("trace")
	sym_true_QMARK_ := lang.NewSymbolUnchecked("true?")
	sym_typeof_STAR_ := lang.NewSymbolUnchecked("typeof*")
	sym_value := lang.NewSymbolUnchecked("value")
	sym_vector_QMARK_ := lang.NewSymbolUnchecked("vector?")
	sym_warn := lang.NewSymbolUnchecked("warn")
	sym_x := lang.NewSymbolUnchecked("x")
	sym_yaml_DASH_parser_DOT_prelude := lang.NewSymbolUnchecked("yaml-parser.prelude")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	kw_value := lang.NewKeyword("value")
	kw_yamlstar_SLASH_get_DASH_name := lang.NewKeyword("yamlstar/get-name")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/chunk-first
	var_clojure_DOT_core_chunk_DASH_first := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_first)
	// var clojure.core/chunk-rest
	var_clojure_DOT_core_chunk_DASH_rest := lang.InternVarName(sym_clojure_DOT_core, sym_chunk_DASH_rest)
	// var clojure.core/chunked-seq?
	var_clojure_DOT_core_chunked_DASH_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_chunked_DASH_seq_QMARK_)
	// var clojure.core/ex-info
	var_clojure_DOT_core_ex_DASH_info := lang.InternVarName(sym_clojure_DOT_core, sym_ex_DASH_info)
	// var clojure.core/false?
	var_clojure_DOT_core_false_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_false_QMARK_)
	// var clojure.core/fn?
	var_clojure_DOT_core_fn_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_fn_QMARK_)
	// var clojure.core/keys
	var_clojure_DOT_core_keys := lang.InternVarName(sym_clojure_DOT_core, sym_keys)
	// var clojure.core/keyword?
	var_clojure_DOT_core_keyword_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_keyword_QMARK_)
	// var clojure.core/map
	var_clojure_DOT_core_map := lang.InternVarName(sym_clojure_DOT_core, sym_map)
	// var clojure.core/map?
	var_clojure_DOT_core_map_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_map_QMARK_)
	// var clojure.core/not-empty
	var_clojure_DOT_core_not_DASH_empty := lang.InternVarName(sym_clojure_DOT_core, sym_not_DASH_empty)
	// var clojure.core/number?
	var_clojure_DOT_core_number_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_number_QMARK_)
	// var clojure.core/pr-str
	var_clojure_DOT_core_pr_DASH_str := lang.InternVarName(sym_clojure_DOT_core, sym_pr_DASH_str)
	// var clojure.core/prn
	var_clojure_DOT_core_prn := lang.InternVarName(sym_clojure_DOT_core, sym_prn)
	// var clojure.core/seq?
	var_clojure_DOT_core_seq_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_seq_QMARK_)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/string?
	var_clojure_DOT_core_string_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_string_QMARK_)
	// var clojure.core/symbol?
	var_clojure_DOT_core_symbol_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_symbol_QMARK_)
	// var clojure.core/true?
	var_clojure_DOT_core_true_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_true_QMARK_)
	// var clojure.core/vector?
	var_clojure_DOT_core_vector_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_vector_QMARK_)
	// var clojure.string/join
	var_clojure_DOT_string_join := lang.InternVarName(sym_clojure_DOT_string, sym_join)
	// var yaml-parser.prelude/DEBUG
	var_yaml_DASH_parser_DOT_prelude_DEBUG := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_DEBUG)
	// var yaml-parser.prelude/FAIL
	var_yaml_DASH_parser_DOT_prelude_FAIL := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_FAIL)
	// var yaml-parser.prelude/GET-NAME-SENTINEL
	var_yaml_DASH_parser_DOT_prelude_GET_DASH_NAME_DASH_SENTINEL := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_GET_DASH_NAME_DASH_SENTINEL)
	// var yaml-parser.prelude/debug
	var_yaml_DASH_parser_DOT_prelude_debug := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_debug)
	// var yaml-parser.prelude/debug-rule
	var_yaml_DASH_parser_DOT_prelude_debug_DASH_rule := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_debug_DASH_rule)
	// var yaml-parser.prelude/die
	var_yaml_DASH_parser_DOT_prelude_die := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_die)
	// var yaml-parser.prelude/die*
	var_yaml_DASH_parser_DOT_prelude_die_STAR_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_die_STAR_)
	// var yaml-parser.prelude/env
	var_yaml_DASH_parser_DOT_prelude_env := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_env)
	// var yaml-parser.prelude/from-code-point
	var_yaml_DASH_parser_DOT_prelude_from_DASH_code_DASH_point := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_from_DASH_code_DASH_point)
	// var yaml-parser.prelude/func-name
	var_yaml_DASH_parser_DOT_prelude_func_DASH_name := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_func_DASH_name)
	// var yaml-parser.prelude/hex-char
	var_yaml_DASH_parser_DOT_prelude_hex_DASH_char := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_hex_DASH_char)
	// var yaml-parser.prelude/is-array?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_array_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_array_QMARK_)
	// var yaml-parser.prelude/is-boolean?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_boolean_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_boolean_QMARK_)
	// var yaml-parser.prelude/is-function?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_function_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_function_QMARK_)
	// var yaml-parser.prelude/is-null?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_null_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_null_QMARK_)
	// var yaml-parser.prelude/is-number?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_number_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_number_QMARK_)
	// var yaml-parser.prelude/is-object?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_object_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_object_QMARK_)
	// var yaml-parser.prelude/is-string?
	var_yaml_DASH_parser_DOT_prelude_is_DASH_string_QMARK_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_is_DASH_string_QMARK_)
	// var yaml-parser.prelude/name*
	var_yaml_DASH_parser_DOT_prelude_name_STAR_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_name_STAR_)
	// var yaml-parser.prelude/stringify
	var_yaml_DASH_parser_DOT_prelude_stringify := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_stringify)
	// var yaml-parser.prelude/timer
	var_yaml_DASH_parser_DOT_prelude_timer := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_timer)
	// var yaml-parser.prelude/typeof*
	var_yaml_DASH_parser_DOT_prelude_typeof_STAR_ := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_typeof_STAR_)
	// var yaml-parser.prelude/warn
	var_yaml_DASH_parser_DOT_prelude_warn := lang.InternVarName(sym_yaml_DASH_parser_DOT_prelude, sym_warn)
	aotExternalFn1 := aotLinkFn1(var_clojure_DOT_core_prn)
	aotExternalFn10 := aotLinkFn2(var_clojure_DOT_string_join)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_core_map)
	aotExternalFn12 := aotLinkFn4(var_clojure_DOT_core_str)
	aotExternalFn13 := aotLinkFn2(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn14 := aotLinkFn1(var_clojure_DOT_core_not_DASH_empty)
	aotExternalFn15 := aotLinkFn1(var_clojure_DOT_core_str)
	aotExternalFn16 := aotLinkFn1(var_clojure_DOT_core_fn_QMARK_)
	aotExternalFn17 := aotLinkFn1(var_clojure_DOT_core_string_QMARK_)
	aotExternalFn18 := aotLinkFn1(var_clojure_DOT_core_vector_QMARK_)
	aotExternalFn19 := aotLinkFn1(var_clojure_DOT_core_seq_QMARK_)
	aotExternalFn2 := aotLinkFn1(var_clojure_DOT_core_chunked_DASH_seq_QMARK_)
	aotExternalFn20 := aotLinkFn1(var_clojure_DOT_core_true_QMARK_)
	aotExternalFn21 := aotLinkFn1(var_clojure_DOT_core_false_QMARK_)
	aotExternalFn22 := aotLinkFn1(var_clojure_DOT_core_number_QMARK_)
	aotExternalFn23 := aotLinkFn1(var_clojure_DOT_core_map_QMARK_)
	aotExternalFn24 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn25 := aotLinkFn1(var_clojure_DOT_core_pr_DASH_str)
	aotExternalFn26 := aotLinkFn1(var_clojure_DOT_core_keys)
	aotExternalFn27 := aotLinkFn1(var_clojure_DOT_core_keyword_QMARK_)
	aotExternalFn28 := aotLinkFn1(var_clojure_DOT_core_symbol_QMARK_)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_first)
	aotExternalFn4 := aotLinkFn1(var_clojure_DOT_core_chunk_DASH_rest)
	aotExternalFn8 := aotLinkFn3(var_clojure_DOT_core_str)
	aotExternalFn9 := aotLinkFn2(var_clojure_DOT_core_str)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	// DEBUG
	{
		tmp0 := sym_DEBUG
		var_yaml_DASH_parser_DOT_prelude_DEBUG = ns.InternWithValue(tmp0, nil, true)
		var_yaml_DASH_parser_DOT_prelude_DEBUG.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(94), kw_column, int(6), kw_end_DASH_line, int(94), kw_end_DASH_column, int(10), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// FAIL
	{
		tmp0 := sym_FAIL
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 any
				{ // let
					// let binding "seq_1"
					tmp4 := lang.Seq(v2)
					var v5 any = tmp4
					_ = v5
					// let binding "chunk_2"
					var v6 any = nil
					_ = v6
					// let binding "count_3"
					var v7 any = int64(0)
					_ = v7
					// let binding "i_4"
					var v8 any = int64(0)
					_ = v8
					for {
						var tmp9 any
						tmp10 := lang.Numbers.Lt(v8, v7)
						if lang.IsTruthy(tmp10) {
							var tmp11 any
							{ // let
								// let binding "o"
								tmp12 := v6.(interface{ Nth(int) any }).Nth(lang.IntCast(v8))
								var v13 any = tmp12
								_ = v13
								tmp14 := aotExternalFn1(v13)
								_ = tmp14
								var tmp15 any = v5
								var tmp16 any = v6
								var tmp17 any = v7
								tmp19 := lang.Numbers.Unchecked_inc(v8)
								var tmp18 any = tmp19
								v5 = tmp15
								v6 = tmp16
								v7 = tmp17
								v8 = tmp18
								continue
							} // end let
							tmp9 = tmp11
						} else {
							var tmp12 any
							{ // let
								// let binding "temp__0__auto__"
								tmp13 := lang.Seq(v5)
								var v14 any = tmp13
								_ = v14
								var tmp15 any
								if lang.IsTruthy(v14) {
									var tmp16 any
									{ // let
										// let binding "seq_1"
										var v17 any = v14
										_ = v17
										var tmp18 any
										tmp19 := aotExternalFn2(v17)
										if lang.IsTruthy(tmp19) {
											var tmp20 any
											{ // let
												// let binding "c__0__auto__"
												tmp21 := aotExternalFn3(v17)
												var v22 any = tmp21
												_ = v22
												tmp24 := aotExternalFn4(v17)
												var tmp23 any = tmp24
												var tmp25 any = v22
												tmp27 := lang.Count(v22)
												tmp28 := runtime.RT.IntCast(tmp27)
												var tmp26 any = tmp28
												tmp30 := runtime.RT.IntCast(int64(0))
												var tmp29 any = tmp30
												v5 = tmp23
												v6 = tmp25
												v7 = tmp26
												v8 = tmp29
												continue
											} // end let
											tmp18 = tmp20
										} else {
											var tmp21 any
											{ // let
												// let binding "o"
												tmp22 := lang.First(v17)
												var v23 any = tmp22
												_ = v23
												tmp24 := aotExternalFn1(v23)
												_ = tmp24
												tmp26 := lang.Next(v17)
												var tmp25 any = tmp26
												var tmp27 any = nil
												var tmp28 any = int64(0)
												var tmp29 any = int64(0)
												v5 = tmp25
												v6 = tmp27
												v7 = tmp28
												v8 = tmp29
												continue
											} // end let
											tmp18 = tmp21
										}
										tmp16 = tmp18
									} // end let
									tmp15 = tmp16
								} else {
								}
								tmp12 = tmp15
							} // end let
							tmp9 = tmp12
						}
						tmp3 = tmp9
						break
					}
				} // end let
				_ = tmp3
				var tmp4 any
				{ // let
					// let binding "or__0__auto__"
					tmp5 := lang.First(v2)
					var v6 any = tmp5
					_ = v6
					var tmp7 any
					if lang.IsTruthy(v6) {
						tmp7 = v6
					} else {
						tmp7 = "???"
					}
					tmp4 = tmp7
				} // end let
				tmp5 := aotExternalFn8("FAIL '", tmp4, "'")
				tmp6 := aotDirectFn3(tmp5)
				return tmp6
			}),
			0,
		)
		aotDirectFn0 = tmp1
		var_yaml_DASH_parser_DOT_prelude_FAIL = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_FAIL.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(101), kw_column, int(7), kw_end_DASH_line, int(101), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// GET-NAME-SENTINEL
	{
		tmp0 := sym_GET_DASH_NAME_DASH_SENTINEL
		var_yaml_DASH_parser_DOT_prelude_GET_DASH_NAME_DASH_SENTINEL = ns.InternWithValue(tmp0, kw_yamlstar_SLASH_get_DASH_name, true)
		var_yaml_DASH_parser_DOT_prelude_GET_DASH_NAME_DASH_SENTINEL.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(33), kw_column, int(14), kw_end_DASH_line, int(33), kw_end_DASH_column, int(30), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// debug
	{
		tmp0 := sym_debug
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn9(">>> ", v2)
			tmp4 := aotDirectFn20(tmp3)
			return tmp4
		})
		aotDirectFn1 = tmp1
		var_yaml_DASH_parser_DOT_prelude_debug = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_debug.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(89), kw_column, int(7), kw_end_DASH_line, int(89), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_msg)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// die
	{
		tmp0 := sym_die
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewMap()
			tmp4 := aotExternalFn13(v2, tmp3)
			panic(tmp4)
		})
		aotDirectFn3 = tmp1
		var_yaml_DASH_parser_DOT_prelude_die = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_die.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(83), kw_column, int(7), kw_end_DASH_line, int(83), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector(sym_msg)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// die*
	{
		tmp0 := sym_die_STAR_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn3(v2)
			return tmp3
		})
		aotDirectFn4 = tmp1
		var_yaml_DASH_parser_DOT_prelude_die_STAR_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_die_STAR_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(86), kw_column, int(7), kw_end_DASH_line, int(86), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_msg)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// env
	{
		tmp0 := sym_env
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.Apply1(os4.Getenv, v2)
			tmp4 := aotExternalFn14(tmp3)
			return tmp4
		})
		aotDirectFn5 = tmp1
		var_yaml_DASH_parser_DOT_prelude_env = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_env.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(5), kw_column, int(7), kw_end_DASH_line, int(5), kw_end_DASH_column, int(9), kw_arglists, lang.NewList(lang.NewVector(sym_key)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// from-code-point
	{
		tmp0 := sym_from_DASH_code_DASH_point
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := runtime.RT.CharCast(v2)
			tmp4 := aotExternalFn15(tmp3)
			return tmp4
		})
		aotDirectFn6 = tmp1
		var_yaml_DASH_parser_DOT_prelude_from_DASH_code_DASH_point = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_from_DASH_code_DASH_point.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(60), kw_column, int(7), kw_end_DASH_line, int(60), kw_end_DASH_column, int(21), kw_arglists, lang.NewList(lang.NewVector(sym_cp)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// func-name
	{
		tmp0 := sym_func_DASH_name
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := aotExternalFn16(v2)
			if lang.IsTruthy(tmp4) {
				var tmp5 any
				func() {
					defer func() {
						if r := recover(); r != nil {
							if lang.CatchMatches(r, lang.Builtins["any"]) {
								v6 := r
								_ = v6
							} else {
								panic(r)
							}
						}
					}()
					var tmp6 any
					{ // let
						// let binding "result"
						tmp7 := checkDerefVar(var_yaml_DASH_parser_DOT_prelude_GET_DASH_NAME_DASH_SENTINEL)
						tmp8 := lang.Apply1(v2, tmp7)
						var v9 any = tmp8
						_ = v9
						var tmp10 any
						tmp11 := aotExternalFn17(v9)
						if lang.IsTruthy(tmp11) {
							tmp10 = v9
						} else {
						}
						tmp6 = tmp10
					} // end let
					tmp5 = tmp6
				}()
				tmp3 = tmp5
			} else {
			}
			return tmp3
		})
		aotDirectFn7 = tmp1
		var_yaml_DASH_parser_DOT_prelude_func_DASH_name = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_func_DASH_name.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(38), kw_column, int(7), kw_end_DASH_line, int(38), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_f)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// hex-char
	{
		tmp0 := sym_hex_DASH_char
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.First(v2)
			tmp4 := runtime.RT.IntCast(tmp3)
			tmp5 := lang.Apply2(fmt.Sprintf, "%x", tmp4)
			return tmp5
		})
		aotDirectFn8 = tmp1
		var_yaml_DASH_parser_DOT_prelude_hex_DASH_char = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_hex_DASH_char.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(74), kw_column, int(7), kw_end_DASH_line, int(74), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_chr)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-array?
	{
		tmp0 := sym_is_DASH_array_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "or__0__auto__"
				tmp4 := aotExternalFn18(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					tmp6 = v5
				} else {
					tmp7 := aotExternalFn19(v2)
					tmp6 = tmp7
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn9 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_array_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_array_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(15), kw_column, int(7), kw_end_DASH_line, int(15), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-boolean?
	{
		tmp0 := sym_is_DASH_boolean_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "or__0__auto__"
				tmp4 := aotExternalFn20(v2)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					tmp6 = v5
				} else {
					tmp7 := aotExternalFn21(v2)
					tmp6 = tmp7
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn10 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_boolean_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_boolean_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(11), kw_column, int(7), kw_end_DASH_line, int(11), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-function?
	{
		tmp0 := sym_is_DASH_function_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn16(v2)
			return tmp3
		})
		aotDirectFn11 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_function_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_function_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(14), kw_column, int(7), kw_end_DASH_line, int(14), kw_end_DASH_column, int(18), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-null?
	{
		tmp0 := sym_is_DASH_null_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.Identical(v2, nil)
			return tmp3
		})
		aotDirectFn12 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_null_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_null_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(10), kw_column, int(7), kw_end_DASH_line, int(10), kw_end_DASH_column, int(14), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-number?
	{
		tmp0 := sym_is_DASH_number_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn22(v2)
			return tmp3
		})
		aotDirectFn13 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_number_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_number_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(12), kw_column, int(7), kw_end_DASH_line, int(12), kw_end_DASH_column, int(16), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-object?
	{
		tmp0 := sym_is_DASH_object_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn23(v2)
			return tmp3
		})
		aotDirectFn14 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_object_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_object_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(16), kw_column, int(7), kw_end_DASH_line, int(16), kw_end_DASH_column, int(16), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// is-string?
	{
		tmp0 := sym_is_DASH_string_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotExternalFn17(v2)
			return tmp3
		})
		aotDirectFn15 = tmp1
		var_yaml_DASH_parser_DOT_prelude_is_DASH_string_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_is_DASH_string_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(13), kw_column, int(7), kw_end_DASH_line, int(13), kw_end_DASH_column, int(16), kw_arglists, lang.NewList(lang.NewVector(sym_x)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// name*
	{
		tmp0 := sym_name_STAR_
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			{ // let
				// let binding "the-trace"
				var tmp6 any
				{ // let
					// let binding "or__0__auto__"
					var v7 any = v4
					_ = v7
					var tmp8 any
					if lang.IsTruthy(v7) {
						tmp8 = v7
					} else {
						tmp8 = v2
					}
					tmp6 = tmp8
				} // end let
				var v7 any = tmp6
				_ = v7
				var tmp8 lang.ArityFn
				tmp8 = lang.NewArityFn(
					nil,
					lang.FnFunc1(func(p0 any) any {
						v9 := p0
						_ = v9
						var tmp10 any
						tmp11 := checkDerefVar(var_yaml_DASH_parser_DOT_prelude_GET_DASH_NAME_DASH_SENTINEL)
						tmp12 := aotExternalFn24(v9, tmp11)
						if lang.IsTruthy(tmp12) {
							tmp10 = v7
						} else {
							tmp13 := lang.Apply1(v3, v9)
							tmp10 = tmp13
						}
						return tmp10
					}),
					lang.FnFunc2(func(p0, p1 any) any {
						v9 := p0
						_ = v9
						v10 := p1
						_ = v10
						tmp11 := lang.Apply2(v3, v9, v10)
						return tmp11
					}),
					lang.FnFunc3(func(p0, p1, p2 any) any {
						v9 := p0
						_ = v9
						v10 := p1
						_ = v10
						v11 := p2
						_ = v11
						tmp12 := lang.Apply3(v3, v9, v10, v11)
						return tmp12
					}),
					nil,
					nil,
					0,
				)
				tmp5 = tmp8
			} // end let
			return tmp5
		})
		aotDirectFn16 = tmp1
		var_yaml_DASH_parser_DOT_prelude_name_STAR_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_name_STAR_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(49), kw_column, int(7), kw_end_DASH_line, int(49), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_name, sym_func, sym_trace)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// stringify
	{
		tmp0 := sym_stringify
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := aotExternalFn24(v2, "\ufeff")
			if lang.IsTruthy(tmp4) {
				tmp3 = "\\uFEFF"
			} else {
				var tmp5 any
				tmp6 := aotExternalFn16(v2)
				if lang.IsTruthy(tmp6) {
					var tmp7 any
					{ // let
						// let binding "or__0__auto__"
						tmp8 := aotDirectFn7(v2)
						var v9 any = tmp8
						_ = v9
						var tmp10 any
						if lang.IsTruthy(v9) {
							tmp10 = v9
						} else {
							tmp10 = "fn"
						}
						tmp7 = tmp10
					} // end let
					tmp8 := aotExternalFn9("@", tmp7)
					tmp5 = tmp8
				} else {
					var tmp9 any
					tmp10 := aotExternalFn23(v2)
					if lang.IsTruthy(tmp10) {
						tmp11 := aotExternalFn26(v2)
						tmp12 := aotExternalFn25(tmp11)
						tmp9 = tmp12
					} else {
						var tmp13 any
						var tmp14 any
						{ // let
							// let binding "or__0__auto__"
							tmp15 := aotExternalFn18(v2)
							var v16 any = tmp15
							_ = v16
							var tmp17 any
							if lang.IsTruthy(v16) {
								tmp17 = v16
							} else {
								tmp18 := aotExternalFn19(v2)
								tmp17 = tmp18
							}
							tmp14 = tmp17
						} // end let
						if lang.IsTruthy(tmp14) {
							tmp15 := checkDerefVar(var_yaml_DASH_parser_DOT_prelude_stringify)
							tmp16 := aotExternalFn11(tmp15, v2)
							tmp17 := aotExternalFn10(",", tmp16)
							tmp18 := aotExternalFn8("[", tmp17, "]")
							tmp13 = tmp18
						} else {
							var tmp19 any
							tmp20 := aotExternalFn17(v2)
							if lang.IsTruthy(tmp20) {
								tmp19 = v2
							} else {
								tmp21 := aotExternalFn25(v2)
								tmp19 = tmp21
							}
							tmp13 = tmp19
						}
						tmp9 = tmp13
					}
					tmp5 = tmp9
				}
				tmp3 = tmp5
			}
			return tmp3
		})
		aotDirectFn17 = tmp1
		var_yaml_DASH_parser_DOT_prelude_stringify = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_stringify.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(65), kw_column, int(7), kw_end_DASH_line, int(65), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_o)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// timer
	{
		tmp0 := sym_timer
		var tmp1 lang.ArityFn
		aotDirectFn18Arity0 = lang.FnFunc0(func() any {
			return int64(0)
		})
		aotDirectFn18Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			return float64(0)
		})
		tmp1 = lang.NewArityFn(
			aotDirectFn18Arity0,
			aotDirectFn18Arity1,
			nil,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn18 = tmp1
		var_yaml_DASH_parser_DOT_prelude_timer = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_timer.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(107), kw_column, int(7), kw_end_DASH_line, int(107), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(), lang.NewVector(sym_start)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// typeof*
	{
		tmp0 := sym_typeof_STAR_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			tmp4 := lang.Identical(v2, nil)
			if lang.IsTruthy(tmp4) {
				tmp3 = "null"
			} else {
				var tmp5 any
				var tmp6 any
				{ // let
					// let binding "or__0__auto__"
					tmp7 := aotExternalFn20(v2)
					var v8 any = tmp7
					_ = v8
					var tmp9 any
					if lang.IsTruthy(v8) {
						tmp9 = v8
					} else {
						tmp10 := aotExternalFn21(v2)
						tmp9 = tmp10
					}
					tmp6 = tmp9
				} // end let
				if lang.IsTruthy(tmp6) {
					tmp5 = "boolean"
				} else {
					var tmp7 any
					tmp8 := aotExternalFn22(v2)
					if lang.IsTruthy(tmp8) {
						tmp7 = "number"
					} else {
						var tmp9 any
						tmp10 := aotExternalFn17(v2)
						if lang.IsTruthy(tmp10) {
							tmp9 = "string"
						} else {
							var tmp11 any
							tmp12 := aotExternalFn27(v2)
							if lang.IsTruthy(tmp12) {
								tmp11 = "string"
							} else {
								var tmp13 any
								tmp14 := aotExternalFn28(v2)
								if lang.IsTruthy(tmp14) {
									tmp13 = "string"
								} else {
									var tmp15 any
									tmp16 := aotExternalFn16(v2)
									if lang.IsTruthy(tmp16) {
										tmp15 = "function"
									} else {
										var tmp17 any
										var tmp18 any
										{ // let
											// let binding "or__0__auto__"
											tmp19 := aotExternalFn18(v2)
											var v20 any = tmp19
											_ = v20
											var tmp21 any
											if lang.IsTruthy(v20) {
												tmp21 = v20
											} else {
												tmp22 := aotExternalFn19(v2)
												tmp21 = tmp22
											}
											tmp18 = tmp21
										} // end let
										if lang.IsTruthy(tmp18) {
											tmp17 = "array"
										} else {
											var tmp19 any
											tmp20 := aotExternalFn23(v2)
											if lang.IsTruthy(tmp20) {
												tmp19 = "object"
											} else {
												tmp21 := lang.NewMap(kw_value, v2)
												tmp22 := aotExternalFn13("Unknown type", tmp21)
												panic(tmp22)
											}
											tmp17 = tmp19
										}
										tmp15 = tmp17
									}
									tmp13 = tmp15
								}
								tmp11 = tmp13
							}
							tmp9 = tmp11
						}
						tmp7 = tmp9
					}
					tmp5 = tmp7
				}
				tmp3 = tmp5
			}
			return tmp3
		})
		aotDirectFn19 = tmp1
		var_yaml_DASH_parser_DOT_prelude_typeof_STAR_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_typeof_STAR_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(18), kw_column, int(7), kw_end_DASH_line, int(18), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_value)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// warn
	{
		tmp0 := sym_warn
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.Apply2(fmt.Fprintln, os4.Stderr, v2)
			return tmp3
		})
		aotDirectFn20 = tmp1
		var_yaml_DASH_parser_DOT_prelude_warn = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_warn.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(79), kw_column, int(7), kw_end_DASH_line, int(79), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_msg)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
	// debug-rule
	{
		tmp0 := sym_debug_DASH_rule
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(1, func(args []any, rest lang.ISeq) any {
				v2 := args[0]
				_ = v2
				var v3 any = rest
				_ = v3
				var tmp4 any
				tmp5 := checkDerefVar(var_yaml_DASH_parser_DOT_prelude_DEBUG)
				if lang.IsTruthy(tmp5) {
					var tmp6 any
					{ // let
						// let binding "args-str"
						tmp7 := checkDerefVar(var_yaml_DASH_parser_DOT_prelude_stringify)
						tmp8 := aotExternalFn11(tmp7, v3)
						tmp9 := aotExternalFn10(",", tmp8)
						var v10 any = tmp9
						_ = v10
						tmp11 := aotExternalFn12(v2, "(", v10, ")")
						tmp12 := aotDirectFn1(tmp11)
						tmp6 = tmp12
					} // end let
					tmp4 = tmp6
				} else {
				}
				return tmp4
			}),
			1,
		)
		aotDirectFn2 = tmp1
		var_yaml_DASH_parser_DOT_prelude_debug_DASH_rule = ns.InternWithValue(tmp0, tmp1, true)
		var_yaml_DASH_parser_DOT_prelude_debug_DASH_rule.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yaml_parser/prelude.glj", kw_line, int(96), kw_column, int(7), kw_end_DASH_line, int(96), kw_end_DASH_column, int(16), kw_arglists, lang.NewList(lang.NewVector(sym_name, sym__AMP_, sym_args)), kw_ns, lang.FindOrCreateNamespace(sym_yaml_DASH_parser_DOT_prelude))
		})
	}
}
