#!/usr/bin/env bash

lang=crystal
tag_prefix=v
root=$(cd "$(dirname "$0")/.." && pwd)

update() (
  rm -fr "${repo_dir:?}"/*

  cp "$root/License" "$repo_dir/LICENSE"
  cp "$from_dir/ReadMe.md" "$repo_dir/README.md"
  cp "$from_dir/shard.yml" "$repo_dir/shard.yml"
  cp -r "$from_dir/examples" "$repo_dir/examples"
  cp -r "$from_dir/spec" "$repo_dir/spec"
  cp -r "$from_dir/src" "$repo_dir/src"
  cp -r "$from_dir/test" "$repo_dir/test"
)

source "$(dirname "$0")/release-repo.bash"

main "$@"
