#!/usr/bin/env bash

lang=nim
tag_prefix=v
root=$(cd "$(dirname "$0")/.." && pwd)

update() (
  cp "$root/License" "$repo_dir/LICENSE"

  cd "$from_dir" || exit
  cp ReadMe.md yamlstar.nimble "$repo_dir/"
  rm -fr "$repo_dir/src" "$repo_dir/tests"
  cp -r src tests "$repo_dir/"
)

source "$(dirname "$0")/release-repo.bash"
