#!/usr/bin/env bash

lang=swift
tag_prefix=v
root=$(cd "$(dirname "$0")/.." && pwd)

update() (
  cp "$root/License" "$repo_dir/LICENSE"

  cd "$from_dir" || exit
  cp ReadMe.md Package.swift "$repo_dir/"
  rm -fr "$repo_dir/Sources" "$repo_dir/Tests"
  cp -r Sources Tests "$repo_dir/"
)

source "$(dirname "$0")/release-repo.bash"
