// Code generated by glojure codegen. DO NOT EDIT.

package desolver

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	regexp4 "regexp"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc1
var aotDirectFn3 lang.FnFunc1
var aotDirectFn4 lang.FnFunc1
var aotDirectFn5 lang.FnFunc1
var aotDirectFn6 lang.FnFunc2
var aotDirectFn7 lang.FnFunc1

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/desolver", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.desolver"
func LoadNS() {
	sym__EQ_ := lang.NewSymbolUnchecked("=")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_clojure_DOT_string := lang.NewSymbolUnchecked("clojure.string")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_core_DASH_tag_QMARK_ := lang.NewSymbolUnchecked("core-tag?")
	sym_desolve := lang.NewSymbolUnchecked("desolve")
	sym_desolve_DASH_all := lang.NewSymbolUnchecked("desolve-all")
	sym_desolve_DASH_node := lang.NewSymbolUnchecked("desolve-node")
	sym_ends_DASH_with_QMARK_ := lang.NewSymbolUnchecked("ends-with?")
	sym_filter := lang.NewSymbolUnchecked("filter")
	sym_implicit_DASH_string_QMARK_ := lang.NewSymbolUnchecked("implicit-string?")
	sym_mapv := lang.NewSymbolUnchecked("mapv")
	sym_node := lang.NewSymbolUnchecked("node")
	sym_nodes := lang.NewSymbolUnchecked("nodes")
	sym_not := lang.NewSymbolUnchecked("not")
	sym_plain_DASH_safe_QMARK_ := lang.NewSymbolUnchecked("plain-safe?")
	sym_re_DASH_find := lang.NewSymbolUnchecked("re-find")
	sym_re_DASH_matches := lang.NewSymbolUnchecked("re-matches")
	sym_scalar_DASH_style := lang.NewSymbolUnchecked("scalar-style")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_string_DASH_tag_QMARK_ := lang.NewSymbolUnchecked("string-tag?")
	sym_tag := lang.NewSymbolUnchecked("tag")
	sym_value := lang.NewSymbolUnchecked("value")
	sym_yamlstar_DOT_desolver := lang.NewSymbolUnchecked("yamlstar.desolver")
	kw_anchor := lang.NewKeyword("anchor")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_flow := lang.NewKeyword("flow")
	kw_kind := lang.NewKeyword("kind")
	kw_line := lang.NewKeyword("line")
	kw_mapping := lang.NewKeyword("mapping")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	kw_scalar := lang.NewKeyword("scalar")
	kw_sequence := lang.NewKeyword("sequence")
	kw_style := lang.NewKeyword("style")
	kw_tag := lang.NewKeyword("tag")
	kw_value := lang.NewKeyword("value")
	// var clojure.core/=
	var_clojure_DOT_core__EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym__EQ_)
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/filter
	var_clojure_DOT_core_filter := lang.InternVarName(sym_clojure_DOT_core, sym_filter)
	// var clojure.core/mapv
	var_clojure_DOT_core_mapv := lang.InternVarName(sym_clojure_DOT_core, sym_mapv)
	// var clojure.core/not
	var_clojure_DOT_core_not := lang.InternVarName(sym_clojure_DOT_core, sym_not)
	// var clojure.core/re-find
	var_clojure_DOT_core_re_DASH_find := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_find)
	// var clojure.core/re-matches
	var_clojure_DOT_core_re_DASH_matches := lang.InternVarName(sym_clojure_DOT_core, sym_re_DASH_matches)
	// var clojure.string/ends-with?
	var_clojure_DOT_string_ends_DASH_with_QMARK_ := lang.InternVarName(sym_clojure_DOT_string, sym_ends_DASH_with_QMARK_)
	// var yamlstar.desolver/core-tag?
	var_yamlstar_DOT_desolver_core_DASH_tag_QMARK_ := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_core_DASH_tag_QMARK_)
	// var yamlstar.desolver/desolve
	var_yamlstar_DOT_desolver_desolve := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_desolve)
	// var yamlstar.desolver/desolve-all
	var_yamlstar_DOT_desolver_desolve_DASH_all := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_desolve_DASH_all)
	// var yamlstar.desolver/desolve-node
	var_yamlstar_DOT_desolver_desolve_DASH_node := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_desolve_DASH_node)
	// var yamlstar.desolver/implicit-string?
	var_yamlstar_DOT_desolver_implicit_DASH_string_QMARK_ := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_implicit_DASH_string_QMARK_)
	// var yamlstar.desolver/plain-safe?
	var_yamlstar_DOT_desolver_plain_DASH_safe_QMARK_ := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_plain_DASH_safe_QMARK_)
	// var yamlstar.desolver/scalar-style
	var_yamlstar_DOT_desolver_scalar_DASH_style := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_scalar_DASH_style)
	// var yamlstar.desolver/string-tag?
	var_yamlstar_DOT_desolver_string_DASH_tag_QMARK_ := lang.InternVarName(sym_yamlstar_DOT_desolver, sym_string_DASH_tag_QMARK_)
	aotExternalFn0 := aotLinkFn2(var_clojure_DOT_core_contains_QMARK_)
	aotExternalFn1 := aotLinkFn2(var_clojure_DOT_core_mapv)
	aotExternalFn3 := aotLinkFn1(var_clojure_DOT_core_not)
	aotExternalFn4 := aotLinkFn2(var_clojure_DOT_core__EQ_)
	aotExternalFn5 := aotLinkFn2(var_clojure_DOT_core_re_DASH_matches)
	aotExternalFn6 := aotLinkFn2(var_clojure_DOT_core_re_DASH_find)
	aotExternalFn8 := aotLinkFn2(var_clojure_DOT_core_filter)
	aotExternalFn9 := aotLinkFn2(var_clojure_DOT_string_ends_DASH_with_QMARK_)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"resolve",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_str, lang.FindOrCreateNamespace(sym_clojure_DOT_string))
	var closed0 any
	var closed1 any
	var closed2 any
	var closed3 any
	var closed4 any
	var closed5 any
	var closed6 any
	var closed7 any
	var closed8 any
	var closed9 any
	{
		closed0 = regexp4.MustCompile("null|Null|NULL|~")
	}
	{
		closed1 = regexp4.MustCompile("true|True|TRUE|false|False|FALSE")
	}
	{
		closed2 = regexp4.MustCompile("[-+]?[0-9]+")
	}
	{
		closed3 = regexp4.MustCompile("[-+]?(\\.[0-9]+|[0-9]+(\\.[0-9]*)?)([eE][-+]?[0-9]+)?")
	}
	{
		closed4 = regexp4.MustCompile("[+-]?(\\.inf|\\.Inf|\\.INF)")
	}
	{
		closed5 = regexp4.MustCompile("\\.nan|\\.NaN|\\.NAN")
	}
	{
		closed6 = regexp4.MustCompile("[#\\[\\]\\{\\},&*?:|>'\\\"%@`]")
	}
	{
		closed7 = regexp4.MustCompile("^\\s|\\s$")
	}
	{
		closed8 = regexp4.MustCompile("\\r|\\n|\\t")
	}
	{
		closed9 = regexp4.MustCompile("^[-?](\\s|$)")
	}
	// core-tag?
	{
		tmp0 := sym_core_DASH_tag_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewSet("tag:yaml.org,2002:int", "tag:yaml.org,2002:str", "tag:yaml.org,2002:float", "!!int", "tag:yaml.org,2002:bool", "!!null", "tag:yaml.org,2002:null", "!!bool", "!!str", "!!float")
			tmp4 := aotExternalFn0(tmp3, v2)
			return tmp4
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_desolver_core_DASH_tag_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_core_DASH_tag_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(22), kw_column, int(8), kw_end_DASH_line, int(22), kw_end_DASH_column, int(16), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_tag)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// desolve
	{
		tmp0 := sym_desolve
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn3(v2)
			return tmp3
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_desolver_desolve = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_desolve.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(72), kw_column, int(7), kw_end_DASH_line, int(72), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_doc, "Prepare a represented node tree for serialization.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// desolve-node
	{
		tmp0 := sym_desolve_DASH_node
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			if lang.IsTruthy(v2) {
				var tmp4 any
				{ // let
					// let binding "G__90"
					tmp5 := kw_kind.Invoke1(v2)
					var v6 any = tmp5
					_ = v6
					// case
					var tmp7 any
					var tmp8 int64
					tmp8 = int64(uint32(lang.IdentityHash(v6)>>2) & uint32(3))
					// case entry 0 (key=1, collision=false)
					if tmp8 == 1 {
						if v6 == kw_mapping {
							var tmp9 any
							{ // let
								// let binding "G__91"
								var tmp10 lang.FnFunc1
								tmp10 = lang.FnFunc1(func(p0 any) any {
									v11 := p0
									_ = v11
									var tmp12 any
									{ // let
										// let binding "vec__93"
										var v13 any = v11
										_ = v13
										// let binding "k"
										tmp14 := runtime.RT.NthDefault(v13, lang.IntCast(int64(0)), nil)
										var v15 any = tmp14
										_ = v15
										// let binding "v"
										tmp16 := runtime.RT.NthDefault(v13, lang.IntCast(int64(1)), nil)
										var v17 any = tmp16
										_ = v17
										tmp18 := aotDirectFn3(v15)
										tmp19 := aotDirectFn3(v17)
										tmp20 := lang.NewVector(tmp18, tmp19)
										tmp12 = tmp20
									} // end let
									return tmp12
								})
								tmp11 := kw_value.Invoke1(v2)
								tmp12 := aotExternalFn1(tmp10, tmp11)
								tmp13 := lang.NewMap(kw_kind, kw_mapping, kw_value, tmp12)
								var v14 any = tmp13
								_ = v14
								// let binding "G__91"
								var tmp15 any
								tmp16 := kw_anchor.Invoke1(v2)
								if lang.IsTruthy(tmp16) {
									tmp17 := kw_anchor.Invoke1(v2)
									var tmp18 any = v14
									tmp18 = lang.Assoc(tmp18, kw_anchor, tmp17)
									tmp15 = tmp18
								} else {
									tmp15 = v14
								}
								var v19 any = tmp15
								_ = v19
								// let binding "G__91"
								var tmp20 any
								tmp21 := kw_flow.Invoke1(v2)
								if lang.IsTruthy(tmp21) {
									tmp22 := kw_flow.Invoke1(v2)
									var tmp23 any = v19
									tmp23 = lang.Assoc(tmp23, kw_flow, tmp22)
									tmp20 = tmp23
								} else {
									tmp20 = v19
								}
								var v24 any = tmp20
								_ = v24
								var tmp25 any
								var tmp26 any
								{ // let
									// let binding "and__0__auto__"
									tmp27 := kw_tag.Invoke1(v2)
									var v28 any = tmp27
									_ = v28
									var tmp29 any
									if lang.IsTruthy(v28) {
										tmp30 := kw_tag.Invoke1(v2)
										tmp31 := aotDirectFn0(tmp30)
										tmp32 := aotExternalFn3(tmp31)
										tmp29 = tmp32
									} else {
										tmp29 = v28
									}
									tmp26 = tmp29
								} // end let
								if lang.IsTruthy(tmp26) {
									tmp27 := kw_tag.Invoke1(v2)
									var tmp28 any = v24
									tmp28 = lang.Assoc(tmp28, kw_tag, tmp27)
									tmp25 = tmp28
								} else {
									tmp25 = v24
								}
								tmp9 = tmp25
							} // end let
							tmp7 = tmp9
						} else {
							tmp7 = v2
						}
						// case entry 1 (key=2, collision=false)
					} else if tmp8 == 2 {
						if v6 == kw_sequence {
							var tmp10 any
							{ // let
								// let binding "G__96"
								tmp11 := checkDerefVar(var_yamlstar_DOT_desolver_desolve_DASH_node)
								tmp12 := kw_value.Invoke1(v2)
								tmp13 := aotExternalFn1(tmp11, tmp12)
								tmp14 := lang.NewMap(kw_kind, kw_sequence, kw_value, tmp13)
								var v15 any = tmp14
								_ = v15
								// let binding "G__96"
								var tmp16 any
								tmp17 := kw_anchor.Invoke1(v2)
								if lang.IsTruthy(tmp17) {
									tmp18 := kw_anchor.Invoke1(v2)
									var tmp19 any = v15
									tmp19 = lang.Assoc(tmp19, kw_anchor, tmp18)
									tmp16 = tmp19
								} else {
									tmp16 = v15
								}
								var v20 any = tmp16
								_ = v20
								// let binding "G__96"
								var tmp21 any
								tmp22 := kw_flow.Invoke1(v2)
								if lang.IsTruthy(tmp22) {
									tmp23 := kw_flow.Invoke1(v2)
									var tmp24 any = v20
									tmp24 = lang.Assoc(tmp24, kw_flow, tmp23)
									tmp21 = tmp24
								} else {
									tmp21 = v20
								}
								var v25 any = tmp21
								_ = v25
								var tmp26 any
								var tmp27 any
								{ // let
									// let binding "and__0__auto__"
									tmp28 := kw_tag.Invoke1(v2)
									var v29 any = tmp28
									_ = v29
									var tmp30 any
									if lang.IsTruthy(v29) {
										tmp31 := kw_tag.Invoke1(v2)
										tmp32 := aotDirectFn0(tmp31)
										tmp33 := aotExternalFn3(tmp32)
										tmp30 = tmp33
									} else {
										tmp30 = v29
									}
									tmp27 = tmp30
								} // end let
								if lang.IsTruthy(tmp27) {
									tmp28 := kw_tag.Invoke1(v2)
									var tmp29 any = v25
									tmp29 = lang.Assoc(tmp29, kw_tag, tmp28)
									tmp26 = tmp29
								} else {
									tmp26 = v25
								}
								tmp10 = tmp26
							} // end let
							tmp7 = tmp10
						} else {
							tmp7 = v2
						}
						// case entry 2 (key=3, collision=false)
					} else if tmp8 == 3 {
						if v6 == kw_scalar {
							var tmp11 any
							{ // let
								// let binding "value"
								tmp12 := kw_value.Invoke1(v2)
								var v13 any = tmp12
								_ = v13
								// let binding "tag"
								tmp14 := kw_tag.Invoke1(v2)
								var v15 any = tmp14
								_ = v15
								var tmp16 any
								{ // let
									// let binding "G__97"
									tmp17 := lang.NewMap(kw_kind, kw_scalar, kw_value, v13)
									var v18 any = tmp17
									_ = v18
									// let binding "G__97"
									var tmp19 any
									tmp20 := aotDirectFn6(v13, v15)
									if lang.IsTruthy(tmp20) {
										tmp21 := aotDirectFn6(v13, v15)
										var tmp22 any = v18
										tmp22 = lang.Assoc(tmp22, kw_style, tmp21)
										tmp19 = tmp22
									} else {
										tmp19 = v18
									}
									var v23 any = tmp19
									_ = v23
									var tmp24 any
									var tmp25 any
									{ // let
										// let binding "and__0__auto__"
										var v26 any = v15
										_ = v26
										var tmp27 any
										if lang.IsTruthy(v26) {
											tmp28 := aotDirectFn7(v15)
											tmp29 := aotExternalFn3(tmp28)
											tmp27 = tmp29
										} else {
											tmp27 = v26
										}
										tmp25 = tmp27
									} // end let
									if lang.IsTruthy(tmp25) {
										var tmp26 any = v23
										tmp26 = lang.Assoc(tmp26, kw_tag, v15)
										tmp24 = tmp26
									} else {
										tmp24 = v23
									}
									tmp16 = tmp24
								} // end let
								tmp11 = tmp16
							} // end let
							tmp7 = tmp11
						} else {
							tmp7 = v2
						}
					} else {
						tmp7 = v2
					}
					tmp4 = tmp7
				} // end let
				tmp3 = tmp4
			} else {
			}
			return tmp3
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_desolver_desolve_DASH_node = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_desolve_DASH_node.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(43), kw_column, int(7), kw_end_DASH_line, int(43), kw_end_DASH_column, int(18), kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_doc, "Remove implicit tags and add style hints where needed.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// implicit-string?
	{
		tmp0 := sym_implicit_DASH_string_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "or__0__auto__"
				tmp4 := aotExternalFn4(v2, "")
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					tmp6 = v5
				} else {
					var tmp7 any
					{ // let
						// let binding "or__0__auto__"
						tmp8 := aotExternalFn5(closed0, v2)
						var v9 any = tmp8
						_ = v9
						var tmp10 any
						if lang.IsTruthy(v9) {
							tmp10 = v9
						} else {
							var tmp11 any
							{ // let
								// let binding "or__0__auto__"
								tmp12 := aotExternalFn5(closed1, v2)
								var v13 any = tmp12
								_ = v13
								var tmp14 any
								if lang.IsTruthy(v13) {
									tmp14 = v13
								} else {
									var tmp15 any
									{ // let
										// let binding "or__0__auto__"
										tmp16 := aotExternalFn5(closed2, v2)
										var v17 any = tmp16
										_ = v17
										var tmp18 any
										if lang.IsTruthy(v17) {
											tmp18 = v17
										} else {
											var tmp19 any
											{ // let
												// let binding "or__0__auto__"
												tmp20 := aotExternalFn5(closed3, v2)
												var v21 any = tmp20
												_ = v21
												var tmp22 any
												if lang.IsTruthy(v21) {
													tmp22 = v21
												} else {
													var tmp23 any
													{ // let
														// let binding "or__0__auto__"
														tmp24 := aotExternalFn5(closed4, v2)
														var v25 any = tmp24
														_ = v25
														var tmp26 any
														if lang.IsTruthy(v25) {
															tmp26 = v25
														} else {
															tmp27 := aotExternalFn5(closed5, v2)
															tmp26 = tmp27
														}
														tmp23 = tmp26
													} // end let
													tmp22 = tmp23
												}
												tmp19 = tmp22
											} // end let
											tmp18 = tmp19
										}
										tmp15 = tmp18
									} // end let
									tmp14 = tmp15
								}
								tmp11 = tmp14
							} // end let
							tmp10 = tmp11
						}
						tmp7 = tmp10
					} // end let
					tmp6 = tmp7
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn4 = tmp1
		var_yamlstar_DOT_desolver_implicit_DASH_string_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_implicit_DASH_string_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(6), kw_column, int(8), kw_end_DASH_line, int(6), kw_end_DASH_column, int(23), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_value)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// plain-safe?
	{
		tmp0 := sym_plain_DASH_safe_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "and__0__auto__"
				tmp4 := aotDirectFn4(v2)
				tmp5 := aotExternalFn3(tmp4)
				var v6 any = tmp5
				_ = v6
				var tmp7 any
				if lang.IsTruthy(v6) {
					var tmp8 any
					{ // let
						// let binding "and__0__auto__"
						tmp9 := aotExternalFn6(closed6, v2)
						tmp10 := aotExternalFn3(tmp9)
						var v11 any = tmp10
						_ = v11
						var tmp12 any
						if lang.IsTruthy(v11) {
							var tmp13 any
							{ // let
								// let binding "and__0__auto__"
								tmp14 := aotExternalFn6(closed7, v2)
								tmp15 := aotExternalFn3(tmp14)
								var v16 any = tmp15
								_ = v16
								var tmp17 any
								if lang.IsTruthy(v16) {
									var tmp18 any
									{ // let
										// let binding "and__0__auto__"
										tmp19 := aotExternalFn6(closed8, v2)
										tmp20 := aotExternalFn3(tmp19)
										var v21 any = tmp20
										_ = v21
										var tmp22 any
										if lang.IsTruthy(v21) {
											tmp23 := aotExternalFn6(closed9, v2)
											tmp24 := aotExternalFn3(tmp23)
											tmp22 = tmp24
										} else {
											tmp22 = v21
										}
										tmp18 = tmp22
									} // end let
									tmp17 = tmp18
								} else {
									tmp17 = v16
								}
								tmp13 = tmp17
							} // end let
							tmp12 = tmp13
						} else {
							tmp12 = v11
						}
						tmp8 = tmp12
					} // end let
					tmp7 = tmp8
				} else {
					tmp7 = v6
				}
				tmp3 = tmp7
			} // end let
			return tmp3
		})
		aotDirectFn5 = tmp1
		var_yamlstar_DOT_desolver_plain_DASH_safe_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_plain_DASH_safe_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(15), kw_column, int(8), kw_end_DASH_line, int(15), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_value)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// scalar-style
	{
		tmp0 := sym_scalar_DASH_style
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			tmp5 := aotExternalFn4(v3, "!!str")
			if lang.IsTruthy(tmp5) {
				var tmp6 any
				{ // let
					// let binding "newline-count"
					tmp7 := lang.NewSet(lang.NewChar(10))
					tmp8 := aotExternalFn8(tmp7, v2)
					tmp9 := lang.Count(tmp8)
					var v10 any = tmp9
					_ = v10
					var tmp11 any
					tmp12 := aotDirectFn5(v2)
					if lang.IsTruthy(tmp12) {
					} else {
						var tmp13 any
						var tmp14 any
						{ // let
							// let binding "and__0__auto__"
							tmp15 := aotExternalFn4(int64(1), v10)
							var v16 any = tmp15
							_ = v16
							var tmp17 any
							if lang.IsTruthy(v16) {
								tmp18 := aotExternalFn9(v2, "\n")
								tmp17 = tmp18
							} else {
								tmp17 = v16
							}
							tmp14 = tmp17
						} // end let
						if lang.IsTruthy(tmp14) {
							tmp13 = "double"
						} else {
							var tmp15 any
							tmp16 := lang.Numbers.IsPos(v10)
							if lang.IsTruthy(tmp16) {
								tmp15 = "literal"
							} else {
								tmp15 = "single"
							}
							tmp13 = tmp15
						}
						tmp11 = tmp13
					}
					tmp6 = tmp11
				} // end let
				tmp4 = tmp6
			} else {
			}
			return tmp4
		})
		aotDirectFn6 = tmp1
		var_yamlstar_DOT_desolver_scalar_DASH_style = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_scalar_DASH_style.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(34), kw_column, int(8), kw_end_DASH_line, int(34), kw_end_DASH_column, int(19), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_value, sym_tag)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// string-tag?
	{
		tmp0 := sym_string_DASH_tag_QMARK_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewSet("tag:yaml.org,2002:str", "!!str")
			tmp4 := aotExternalFn0(tmp3, v2)
			return tmp4
		})
		aotDirectFn7 = tmp1
		var_yamlstar_DOT_desolver_string_DASH_tag_QMARK_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_string_DASH_tag_QMARK_.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(31), kw_column, int(8), kw_end_DASH_line, int(31), kw_end_DASH_column, int(18), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_tag)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
	// desolve-all
	{
		tmp0 := sym_desolve_DASH_all
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := checkDerefVar(var_yamlstar_DOT_desolver_desolve_DASH_node)
			tmp4 := aotExternalFn1(tmp3, v2)
			return tmp4
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_desolver_desolve_DASH_all = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_desolver_desolve_DASH_all.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/desolver.glj", kw_line, int(77), kw_column, int(7), kw_end_DASH_line, int(77), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_nodes)), kw_doc, "Prepare represented node trees for serialization.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_desolver))
		})
	}
}
