// Code generated by glojure codegen. DO NOT EDIT.

package reference

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	atomic "sync/atomic"
)

var aotKeywordMapShape0 = lang.NewKeywordMapShape("name", "emit", "default-config")

type aotKeywordMapStorage0 struct {
	lang.Map
	values [3]any
}

func aotKeywordMapNew0(v0 any, v1 any, v2 any) lang.IPersistentMap {
	storage := &aotKeywordMapStorage0{}
	storage.values = [3]any{v0, v1, v2}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape0,
		storage.values[:],
	)
}
func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var linked atomic.Pointer[lang.FnFunc2]
	return func(p0 any, p1 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1)
		}
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		fn := aotLinkBoundFn2(vr)
		linked.Store(&fn)
		return fn(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn2(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/plugin/yaml_emitter/reference", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.plugin.yaml-emitter.reference"
func LoadNS() {
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_emit := lang.NewSymbolUnchecked("emit")
	sym_emitter := lang.NewSymbolUnchecked("emitter")
	sym_plugin := lang.NewSymbolUnchecked("plugin")
	sym_yamlstar_DOT_emitter := lang.NewSymbolUnchecked("yamlstar.emitter")
	sym_yamlstar_DOT_plugin := lang.NewSymbolUnchecked("yamlstar.plugin")
	sym_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference := lang.NewSymbolUnchecked("yamlstar.plugin.yaml-emitter.reference")
	kw_column := lang.NewKeyword("column")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_ns := lang.NewKeyword("ns")
	// var yamlstar.emitter/emit
	var_yamlstar_DOT_emitter_emit := lang.InternVarName(sym_yamlstar_DOT_emitter, sym_emit)
	// var yamlstar.plugin.yaml-emitter.reference/plugin
	var_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference_plugin := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference, sym_plugin)
	aotExternalFn0 := aotLinkFn2(var_yamlstar_DOT_emitter_emit)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_emitter, lang.FindOrCreateNamespace(sym_yamlstar_DOT_emitter))
	ns.AddAlias(sym_plugin, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin))
	// plugin
	{
		tmp0 := sym_plugin
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			tmp5 := aotExternalFn0(v2, v3)
			return tmp5
		})
		var_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference_plugin = ns.InternWithValue(tmp0, aotKeywordMapNew0("reference", tmp1, lang.NewMap()), true)
		var_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference_plugin.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar/plugin/yaml_emitter/reference.clj", kw_line, int(6), kw_column, int(6), kw_end_DASH_line, int(6), kw_end_DASH_column, int(11), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_yaml_DASH_emitter_DOT_reference))
		}, false)
	}
}
