// Code generated by glojure codegen. DO NOT EDIT.

package parser

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	atomic "sync/atomic"
)

var aotDirectFn0 lang.FnFunc0
var aotDirectFn1 lang.ArityFn
var aotDirectFn1Arity1 lang.FnFunc1
var aotDirectFn1Arity2 lang.FnFunc2
var aotDirectFn2 lang.ArityFn
var aotDirectFn3 lang.FnFunc0
var aotDirectFn4 lang.FnFunc1

var aotKeywordSite0 lang.KeywordSite
var aotKeywordMapShape0 = lang.NewKeywordMapShape("parser")

type aotKeywordMapStorage0 struct {
	lang.Map
	values [1]any
}

func aotKeywordMapNew0(v0 any) lang.IPersistentMap {
	storage := &aotKeywordMapStorage0{}
	storage.values = [1]any{v0}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape0,
		storage.values[:],
	)
}

var aotKeywordSite1 lang.KeywordSite

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var linked atomic.Pointer[lang.FnFunc1]
	return func(p0 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0)
		}
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		fn := aotLinkBoundFn1(vr)
		linked.Store(&fn)
		return fn(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn1(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var linked atomic.Pointer[lang.FnFunc2]
	return func(p0 any, p1 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1)
		}
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		fn := aotLinkBoundFn2(vr)
		linked.Store(&fn)
		return fn(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn2(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var linked atomic.Pointer[lang.FnFunc3]
	return func(p0 any, p1 any, p2 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2)
		}
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		fn := aotLinkBoundFn3(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn3(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func aotLinkFn4(vr *lang.Var) lang.FnFunc4 {
	if vr.IsBound() {
		return aotLinkBoundFn4(vr)
	}
	var linked atomic.Pointer[lang.FnFunc4]
	return func(p0 any, p1 any, p2 any, p3 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2, p3)
		}
		if !vr.IsBound() {
			return lang.Apply4(checkDerefVar(vr), p0, p1, p2, p3)
		}
		fn := aotLinkBoundFn4(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2, p3)
	}
}

func aotLinkBoundFn4(vr *lang.Var) lang.FnFunc4 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn4(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn4); ok {
		return fixed.Invoke4
	}
	return func(p0 any, p1 any, p2 any, p3 any) any { return lang.Apply4(fn, p0, p1, p2, p3) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/parser", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.parser"
func LoadNS() {
	sym__AMP_ := lang.NewSymbolUnchecked("&")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_contains_QMARK_ := lang.NewSymbolUnchecked("contains?")
	sym_current_DASH_default_DASH_parser := lang.NewSymbolUnchecked("current-default-parser")
	sym_ex_DASH_info := lang.NewSymbolUnchecked("ex-info")
	sym_fallback_DASH_default_DASH_parser := lang.NewSymbolUnchecked("fallback-default-parser")
	sym_json_DASH_comments_DASH_opts := lang.NewSymbolUnchecked("json-comments-opts")
	sym_mapv := lang.NewSymbolUnchecked("mapv")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_names := lang.NewSymbolUnchecked("names")
	sym_not_EQ_ := lang.NewSymbolUnchecked("not=")
	sym_opts := lang.NewSymbolUnchecked("opts")
	sym_parse := lang.NewSymbolUnchecked("parse")
	sym_parse_DASH_with := lang.NewSymbolUnchecked("parse-with")
	sym_parser_DASH_opts := lang.NewSymbolUnchecked("parser-opts")
	sym_plugin := lang.NewSymbolUnchecked("plugin")
	sym_register_DASH_parser_BANG_ := lang.NewSymbolUnchecked("register-parser!")
	sym_register_DASH_parsers_BANG_ := lang.NewSymbolUnchecked("register-parsers!")
	sym_register_DASH_reference_DASH_parser_BANG_ := lang.NewSymbolUnchecked("register-reference-parser!")
	sym_reset_BANG_ := lang.NewSymbolUnchecked("reset!")
	sym_resolve_DASH_parser := lang.NewSymbolUnchecked("resolve-parser")
	sym_sanitize_DASH_with := lang.NewSymbolUnchecked("sanitize-with")
	sym_set_DASH_default_DASH_parser_BANG_ := lang.NewSymbolUnchecked("set-default-parser!")
	sym_tab_DASH_indent_DASH_config := lang.NewSymbolUnchecked("tab-indent-config")
	sym_true_QMARK_ := lang.NewSymbolUnchecked("true?")
	sym_yaml_DASH_str := lang.NewSymbolUnchecked("yaml-str")
	sym_yamlstar_DOT_parser := lang.NewSymbolUnchecked("yamlstar.parser")
	sym_yamlstar_DOT_plugin := lang.NewSymbolUnchecked("yamlstar.plugin")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_load := lang.NewKeyword("load")
	kw_ns := lang.NewKeyword("ns")
	kw_plugin_DASH_install := lang.NewKeyword("plugin-install")
	kw_private := lang.NewKeyword("private")
	kw_tab_DASH_indent := lang.NewKeyword("tab-indent")
	// var clojure.core/contains?
	var_clojure_DOT_core_contains_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_contains_QMARK_)
	// var clojure.core/ex-info
	var_clojure_DOT_core_ex_DASH_info := lang.InternVarName(sym_clojure_DOT_core, sym_ex_DASH_info)
	// var clojure.core/mapv
	var_clojure_DOT_core_mapv := lang.InternVarName(sym_clojure_DOT_core, sym_mapv)
	// var clojure.core/not=
	var_clojure_DOT_core_not_EQ_ := lang.InternVarName(sym_clojure_DOT_core, sym_not_EQ_)
	// var clojure.core/reset!
	var_clojure_DOT_core_reset_BANG_ := lang.InternVarName(sym_clojure_DOT_core, sym_reset_BANG_)
	// var clojure.core/true?
	var_clojure_DOT_core_true_QMARK_ := lang.InternVarName(sym_clojure_DOT_core, sym_true_QMARK_)
	// var yamlstar.parser/current-default-parser
	var_yamlstar_DOT_parser_current_DASH_default_DASH_parser := lang.InternVarName(sym_yamlstar_DOT_parser, sym_current_DASH_default_DASH_parser)
	// var yamlstar.parser/fallback-default-parser
	var_yamlstar_DOT_parser_fallback_DASH_default_DASH_parser := lang.InternVarName(sym_yamlstar_DOT_parser, sym_fallback_DASH_default_DASH_parser)
	// var yamlstar.parser/parse
	var_yamlstar_DOT_parser_parse := lang.InternVarName(sym_yamlstar_DOT_parser, sym_parse)
	// var yamlstar.parser/register-parsers!
	var_yamlstar_DOT_parser_register_DASH_parsers_BANG_ := lang.InternVarName(sym_yamlstar_DOT_parser, sym_register_DASH_parsers_BANG_)
	// var yamlstar.parser/register-reference-parser!
	var_yamlstar_DOT_parser_register_DASH_reference_DASH_parser_BANG_ := lang.InternVarName(sym_yamlstar_DOT_parser, sym_register_DASH_reference_DASH_parser_BANG_)
	// var yamlstar.parser/set-default-parser!
	var_yamlstar_DOT_parser_set_DASH_default_DASH_parser_BANG_ := lang.InternVarName(sym_yamlstar_DOT_parser, sym_set_DASH_default_DASH_parser_BANG_)
	// var yamlstar.plugin/json-comments-opts
	var_yamlstar_DOT_plugin_json_DASH_comments_DASH_opts := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_json_DASH_comments_DASH_opts)
	// var yamlstar.plugin/parse-with
	var_yamlstar_DOT_plugin_parse_DASH_with := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_parse_DASH_with)
	// var yamlstar.plugin/parser-opts
	var_yamlstar_DOT_plugin_parser_DASH_opts := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_parser_DASH_opts)
	// var yamlstar.plugin/register-parser!
	var_yamlstar_DOT_plugin_register_DASH_parser_BANG_ := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_register_DASH_parser_BANG_)
	// var yamlstar.plugin/resolve-parser
	var_yamlstar_DOT_plugin_resolve_DASH_parser := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_resolve_DASH_parser)
	// var yamlstar.plugin/sanitize-with
	var_yamlstar_DOT_plugin_sanitize_DASH_with := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_sanitize_DASH_with)
	// var yamlstar.plugin/tab-indent-config
	var_yamlstar_DOT_plugin_tab_DASH_indent_DASH_config := lang.InternVarName(sym_yamlstar_DOT_plugin, sym_tab_DASH_indent_DASH_config)
	aotExternalFn1 := aotLinkFn1(var_yamlstar_DOT_plugin_json_DASH_comments_DASH_opts)
	aotExternalFn10 := aotLinkFn1(var_clojure_DOT_core_true_QMARK_)
	aotExternalFn11 := aotLinkFn2(var_clojure_DOT_core_mapv)
	aotExternalFn12 := aotLinkFn1(var_yamlstar_DOT_plugin_register_DASH_parser_BANG_)
	aotExternalFn13 := aotLinkFn1(var_yamlstar_DOT_plugin_resolve_DASH_parser)
	aotExternalFn15 := aotLinkFn2(var_clojure_DOT_core_reset_BANG_)
	aotExternalFn2 := aotLinkFn2(var_yamlstar_DOT_plugin_sanitize_DASH_with)
	aotExternalFn3 := aotLinkFn1(var_yamlstar_DOT_plugin_tab_DASH_indent_DASH_config)
	aotExternalFn4 := aotLinkFn2(var_clojure_DOT_core_contains_QMARK_)
	aotExternalFn5 := aotLinkFn1(var_yamlstar_DOT_plugin_parser_DASH_opts)
	aotExternalFn7 := aotLinkFn2(var_clojure_DOT_core_not_EQ_)
	aotExternalFn8 := aotLinkFn2(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn9 := aotLinkFn4(var_yamlstar_DOT_plugin_parse_DASH_with)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	ns.AddAlias(sym_plugin, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin))
	// fallback-default-parser
	{
		tmp0 := sym_fallback_DASH_default_DASH_parser
		tmp1 := lang.NewAtom("reference")
		var_yamlstar_DOT_parser_fallback_DASH_default_DASH_parser = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_fallback_DASH_default_DASH_parser.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar/parser.clj", kw_line, int(28), kw_column, int(6), kw_end_DASH_line, int(28), kw_end_DASH_column, int(38), kw_private, true, kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
	// parse
	{
		tmp0 := sym_parse
		var tmp1 lang.ArityFn
		aotDirectFn1Arity1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := aotDirectFn1Arity2(v2, nil)
			return tmp3
		})
		aotDirectFn1Arity2 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			{ // let
				// let binding "yaml-str"
				var tmp5 any
				{ // let
					// let binding "temp__0__auto__"
					tmp6 := aotExternalFn1(v3)
					var v7 any = tmp6
					_ = v7
					var tmp8 any
					if lang.IsTruthy(v7) {
						var tmp9 any
						{ // let
							// let binding "comments"
							var v10 any = v7
							_ = v10
							tmp11 := aotExternalFn2(v10, v2)
							tmp9 = tmp11
						} // end let
						tmp8 = tmp9
					} else {
						tmp8 = v2
					}
					tmp5 = tmp8
				} // end let
				var v6 any = tmp5
				_ = v6
				// let binding "tabs"
				tmp7 := aotExternalFn3(v3)
				var v8 any = tmp7
				_ = v8
				// let binding "native-tabs"
				var tmp9 any
				{ // let
					// let binding "and__0__auto__"
					var v10 any = v8
					_ = v10
					var tmp11 any
					if lang.IsTruthy(v10) {
						tmp12 := lang.NewSet("tabs", "auto")
						tmp13 := aotKeywordSite0.Get(kw_load, v8, nil)
						tmp14 := aotExternalFn4(tmp12, tmp13)
						tmp11 = tmp14
					} else {
						tmp11 = v10
					}
					tmp9 = tmp11
				} // end let
				var v10 any = tmp9
				_ = v10
				// let binding "vec__40"
				var tmp11 any
				{ // let
					// let binding "or__0__auto__"
					tmp12 := aotExternalFn5(v3)
					var v13 any = tmp12
					_ = v13
					var tmp14 any
					if lang.IsTruthy(v13) {
						tmp14 = v13
					} else {
						tmp15 := aotDirectFn0()
						tmp16 := lang.NewMap()
						tmp17 := lang.NewVector(tmp15, tmp16)
						tmp14 = tmp17
					}
					tmp11 = tmp14
				} // end let
				var v12 any = tmp11
				_ = v12
				// let binding "pname"
				tmp13 := runtime.RT.NthDefault(v12, lang.IntCast(int64(0)), nil)
				var v14 any = tmp13
				_ = v14
				// let binding "config"
				tmp15 := runtime.RT.NthDefault(v12, lang.IntCast(int64(1)), nil)
				var v16 any = tmp15
				_ = v16
				var tmp17 any
				var tmp18 any
				{ // let
					// let binding "and__0__auto__"
					var v19 any = v10
					_ = v19
					var tmp20 any
					if lang.IsTruthy(v19) {
						tmp21 := aotExternalFn7(v14, "go-yaml")
						tmp20 = tmp21
					} else {
						tmp20 = v19
					}
					tmp18 = tmp20
				} // end let
				if lang.IsTruthy(tmp18) {
					tmp19 := aotKeywordMapNew0(v14)
					tmp20 := aotExternalFn8("tab-indent loading requires the native go-yaml parser", tmp19)
					panic(tmp20)
				} else {
				}
				_ = tmp17
				var tmp21 any
				{ // let
					// let binding "G__43"
					var v22 any = v16
					_ = v22
					var tmp23 any
					if lang.IsTruthy(v8) {
						var tmp24 any = v22
						tmp24 = lang.Assoc(tmp24, kw_tab_DASH_indent, v8)
						tmp23 = tmp24
					} else {
						tmp23 = v22
					}
					tmp21 = tmp23
				} // end let
				tmp22 := aotKeywordSite1.Get(kw_plugin_DASH_install, v3, nil)
				tmp23 := aotExternalFn10(tmp22)
				tmp24 := aotExternalFn9(v14, tmp21, v6, tmp23)
				tmp4 = tmp24
			} // end let
			return tmp4
		})
		tmp1 = lang.NewArityFn(
			nil,
			aotDirectFn1Arity1,
			aotDirectFn1Arity2,
			nil,
			nil,
			nil,
			0,
		)
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_parser_parse = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_parse.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/parser.clj", kw_line, int(43), kw_column, int(7), kw_end_DASH_line, int(43), kw_end_DASH_column, int(11), kw_arglists, lang.NewList(lang.NewVector(sym_yaml_DASH_str), lang.NewVector(sym_yaml_DASH_str, sym_opts)), kw_doc, "Parse a YAML string into an event stream.\n\n  Args:\n    yaml-str: A string containing YAML content\n    opts: (optional) Options map with an optional :parser plugin\n\n  Returns:\n    A sequence of event maps representing the YAML structure", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
	// register-parsers!
	{
		tmp0 := sym_register_DASH_parsers_BANG_
		var tmp1 lang.ArityFn
		tmp1 = lang.NewArityFn(
			nil,
			nil,
			nil,
			nil,
			nil,
			lang.NewVariadicFn(0, func(args []any, rest lang.ISeq) any {
				var v2 any = rest
				_ = v2
				var tmp3 lang.FnFunc1
				tmp3 = lang.FnFunc1(func(p0 any) any {
					v4 := p0
					_ = v4
					tmp5 := aotExternalFn13(v4)
					tmp6 := aotExternalFn12(tmp5)
					return tmp6
				})
				tmp4 := aotExternalFn11(tmp3, v2)
				return tmp4
			}),
			0,
		)
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_parser_register_DASH_parsers_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_register_DASH_parsers_BANG_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/parser.clj", kw_line, int(10), kw_column, int(7), kw_end_DASH_line, int(10), kw_end_DASH_column, int(23), kw_arglists, lang.NewList(lang.NewVector(sym__AMP_, sym_names)), kw_doc, "Register the named parser plugins whose namespaces are already loaded.\n\n  Each plugin namespace self-registers with a top-level form, but AOT\n  compiled runtimes (Glojure) drop top-level side effects, so generated\n  runtimes call this explicitly after loading their plugin namespaces.\n  Returns the registered plugin maps in the given order.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
	// register-reference-parser!
	{
		tmp0 := sym_register_DASH_reference_DASH_parser_BANG_
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn2.Invoke1("reference")
			tmp3 := lang.First(tmp2)
			return tmp3
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_parser_register_DASH_reference_DASH_parser_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_register_DASH_reference_DASH_parser_BANG_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/parser.clj", kw_line, int(21), kw_column, int(7), kw_end_DASH_line, int(21), kw_end_DASH_column, int(32), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Register the built-in reference parser plugin.\n\n  Generated runtimes call this after loading their reference parser plugin.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
	// set-default-parser!
	{
		tmp0 := sym_set_DASH_default_DASH_parser_BANG_
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := checkDerefVar(var_yamlstar_DOT_parser_fallback_DASH_default_DASH_parser)
			tmp4 := aotExternalFn15(tmp3, v2)
			_ = tmp4
			return v2
		})
		aotDirectFn4 = tmp1
		var_yamlstar_DOT_parser_set_DASH_default_DASH_parser_BANG_ = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_set_DASH_default_DASH_parser_BANG_.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/parser.clj", kw_line, int(30), kw_column, int(7), kw_end_DASH_line, int(30), kw_end_DASH_column, int(25), kw_arglists, lang.NewList(lang.NewVector(sym_name)), kw_doc, "Set the runtime fallback parser name.\n\n  Per-call options have precedence over this fallback.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
	// current-default-parser
	{
		tmp0 := sym_current_DASH_default_DASH_parser
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			var tmp2 any
			{ // let
				// let binding "or__0__auto__"
				tmp3 := checkDerefVar(var_yamlstar_DOT_parser_fallback_DASH_default_DASH_parser)
				tmp4 := lang.DerefValue(tmp3)
				var v5 any = tmp4
				_ = v5
				var tmp6 any
				if lang.IsTruthy(v5) {
					tmp6 = v5
				} else {
					tmp6 = "reference"
				}
				tmp2 = tmp6
			} // end let
			return tmp2
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_parser_current_DASH_default_DASH_parser = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_parser_current_DASH_default_DASH_parser.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/parser.clj", kw_line, int(38), kw_column, int(8), kw_end_DASH_line, int(38), kw_end_DASH_column, int(29), kw_private, true, kw_arglists, lang.NewList(lang.NewVector()), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_parser))
		}, false)
	}
}
