// Code generated by glojure codegen. DO NOT EDIT.

package serializer

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	sync "sync"
)

var aotDirectFn0 lang.FnFunc1
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc1

func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var once sync.Once
	var linked lang.FnFunc1
	return func(p0 any) any {
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		once.Do(func() { linked = aotLinkBoundFn1(vr) })
		return linked(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc1); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var once sync.Once
	var linked lang.FnFunc2
	return func(p0 any, p1 any) any {
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		once.Do(func() { linked = aotLinkBoundFn2(vr) })
		return linked(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc2); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var once sync.Once
	var linked lang.FnFunc3
	return func(p0 any, p1 any, p2 any) any {
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		once.Do(func() { linked = aotLinkBoundFn3(vr) })
		return linked(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := fn.(lang.FnFunc3); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/serializer", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.serializer"
func LoadNS() {
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_concat := lang.NewSymbolUnchecked("concat")
	sym_mapcat := lang.NewSymbolUnchecked("mapcat")
	sym_node := lang.NewSymbolUnchecked("node")
	sym_nodes := lang.NewSymbolUnchecked("nodes")
	sym_serialize := lang.NewSymbolUnchecked("serialize")
	sym_serialize_DASH_all := lang.NewSymbolUnchecked("serialize-all")
	sym_serialize_DASH_node := lang.NewSymbolUnchecked("serialize-node")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_vec := lang.NewSymbolUnchecked("vec")
	sym_yamlstar_DOT_serializer := lang.NewSymbolUnchecked("yamlstar.serializer")
	kw_alias := lang.NewKeyword("alias")
	kw_anchor := lang.NewKeyword("anchor")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_event := lang.NewKeyword("event")
	kw_file := lang.NewKeyword("file")
	kw_flow := lang.NewKeyword("flow")
	kw_kind := lang.NewKeyword("kind")
	kw_line := lang.NewKeyword("line")
	kw_mapping := lang.NewKeyword("mapping")
	kw_name := lang.NewKeyword("name")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	kw_scalar := lang.NewKeyword("scalar")
	kw_sequence := lang.NewKeyword("sequence")
	kw_style := lang.NewKeyword("style")
	kw_tag := lang.NewKeyword("tag")
	kw_value := lang.NewKeyword("value")
	// var clojure.core/concat
	var_clojure_DOT_core_concat := lang.InternVarName(sym_clojure_DOT_core, sym_concat)
	// var clojure.core/mapcat
	var_clojure_DOT_core_mapcat := lang.InternVarName(sym_clojure_DOT_core, sym_mapcat)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var clojure.core/vec
	var_clojure_DOT_core_vec := lang.InternVarName(sym_clojure_DOT_core, sym_vec)
	// var yamlstar.serializer/serialize
	var_yamlstar_DOT_serializer_serialize := lang.InternVarName(sym_yamlstar_DOT_serializer, sym_serialize)
	// var yamlstar.serializer/serialize-all
	var_yamlstar_DOT_serializer_serialize_DASH_all := lang.InternVarName(sym_yamlstar_DOT_serializer, sym_serialize_DASH_all)
	// var yamlstar.serializer/serialize-node
	var_yamlstar_DOT_serializer_serialize_DASH_node := lang.InternVarName(sym_yamlstar_DOT_serializer, sym_serialize_DASH_node)
	aotExternalFn0 := aotLinkFn1(var_clojure_DOT_core_vec)
	aotExternalFn1 := aotLinkFn3(var_clojure_DOT_core_concat)
	aotExternalFn2 := aotLinkFn2(var_clojure_DOT_core_mapcat)
	aotExternalFn3 := aotLinkFn2(var_clojure_DOT_core_str)
	aotExternalFn5 := aotLinkFn2(var_clojure_DOT_core_concat)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_serializer)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// serialize
	{
		tmp0 := sym_serialize
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewMap(kw_event, "stream_start")
			tmp4 := lang.NewMap(kw_event, "document_start")
			tmp5 := lang.NewVector(tmp3, tmp4)
			var tmp6 any
			if lang.IsTruthy(v2) {
				tmp7 := aotDirectFn2(v2)
				tmp6 = tmp7
			} else {
			}
			tmp8 := lang.NewMap(kw_event, "document_end")
			tmp9 := lang.NewMap(kw_event, "stream_end")
			tmp10 := lang.NewVector(tmp8, tmp9)
			tmp11 := aotExternalFn1(tmp5, tmp6, tmp10)
			tmp12 := aotExternalFn0(tmp11)
			return tmp12
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_serializer_serialize = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_serializer_serialize.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/serializer.glj", kw_line, int(36), kw_column, int(7), kw_end_DASH_line, int(36), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_doc, "Serialize one YAML node tree to an event stream.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_serializer))
		})
	}
	// serialize-all
	{
		tmp0 := sym_serialize_DASH_all
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewMap(kw_event, "stream_start")
			tmp4 := lang.NewVector(tmp3)
			var tmp5 lang.FnFunc1
			tmp5 = lang.FnFunc1(func(p0 any) any {
				v6 := p0
				_ = v6
				tmp7 := lang.NewMap(kw_event, "document_start")
				tmp8 := lang.NewVector(tmp7)
				var tmp9 any
				if lang.IsTruthy(v6) {
					tmp10 := aotDirectFn2(v6)
					tmp9 = tmp10
				} else {
				}
				tmp11 := lang.NewMap(kw_event, "document_end")
				tmp12 := lang.NewVector(tmp11)
				tmp13 := aotExternalFn1(tmp8, tmp9, tmp12)
				return tmp13
			})
			tmp6 := aotExternalFn2(tmp5, v2)
			tmp7 := lang.NewMap(kw_event, "stream_end")
			tmp8 := lang.NewVector(tmp7)
			tmp9 := aotExternalFn1(tmp4, tmp6, tmp8)
			tmp10 := aotExternalFn0(tmp9)
			return tmp10
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_serializer_serialize_DASH_all = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_serializer_serialize_DASH_all.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/serializer.glj", kw_line, int(44), kw_column, int(7), kw_end_DASH_line, int(44), kw_end_DASH_column, int(19), kw_arglists, lang.NewList(lang.NewVector(sym_nodes)), kw_doc, "Serialize multiple YAML node trees to an event stream.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_serializer))
		})
	}
	// serialize-node
	{
		tmp0 := sym_serialize_DASH_node
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			var tmp3 any
			{ // let
				// let binding "G__1"
				tmp4 := kw_kind.Invoke1(v2)
				var v5 any = tmp4
				_ = v5
				// case
				var tmp6 any
				var tmp7 int64
				tmp7 = int64(uint32(lang.IdentityHash(v5)>>3) & uint32(3))
				// case entry 0 (key=0, collision=false)
				if tmp7 == 0 {
					if v5 == kw_alias {
						tmp8 := kw_name.Invoke1(v2)
						tmp9 := lang.NewMap(kw_event, "alias", kw_name, tmp8)
						tmp10 := lang.NewVector(tmp9)
						tmp6 = tmp10
					} else {
						tmp11 := aotExternalFn3("No matching clause: ", v5)
						tmp12 := lang.Apply1(lang.NewIllegalArgumentError, tmp11)
						panic(tmp12)
					}
					// case entry 1 (key=1, collision=false)
				} else if tmp7 == 1 {
					if v5 == kw_scalar {
						var tmp13 any
						{ // let
							// let binding "G__2"
							tmp14 := kw_value.Invoke1(v2)
							tmp15 := lang.NewMap(kw_event, "scalar", kw_value, tmp14)
							var v16 any = tmp15
							_ = v16
							// let binding "G__2"
							var tmp17 any
							tmp18 := kw_anchor.Invoke1(v2)
							if lang.IsTruthy(tmp18) {
								tmp19 := kw_anchor.Invoke1(v2)
								var tmp20 any = v16
								tmp20 = lang.Assoc(tmp20, kw_anchor, tmp19)
								tmp17 = tmp20
							} else {
								tmp17 = v16
							}
							var v21 any = tmp17
							_ = v21
							// let binding "G__2"
							var tmp22 any
							tmp23 := kw_tag.Invoke1(v2)
							if lang.IsTruthy(tmp23) {
								tmp24 := kw_tag.Invoke1(v2)
								var tmp25 any = v21
								tmp25 = lang.Assoc(tmp25, kw_tag, tmp24)
								tmp22 = tmp25
							} else {
								tmp22 = v21
							}
							var v26 any = tmp22
							_ = v26
							var tmp27 any
							tmp28 := kw_style.Invoke1(v2)
							if lang.IsTruthy(tmp28) {
								tmp29 := kw_style.Invoke1(v2)
								var tmp30 any = v26
								tmp30 = lang.Assoc(tmp30, kw_style, tmp29)
								tmp27 = tmp30
							} else {
								tmp27 = v26
							}
							tmp13 = tmp27
						} // end let
						tmp14 := lang.NewVector(tmp13)
						tmp6 = tmp14
					} else {
						tmp15 := aotExternalFn3("No matching clause: ", v5)
						tmp16 := lang.Apply1(lang.NewIllegalArgumentError, tmp15)
						panic(tmp16)
					}
					// case entry 2 (key=2, collision=false)
				} else if tmp7 == 2 {
					if v5 == kw_mapping {
						var tmp17 any
						{ // let
							// let binding "G__3"
							tmp18 := lang.NewMap(kw_event, "mapping_start")
							var v19 any = tmp18
							_ = v19
							// let binding "G__3"
							var tmp20 any
							tmp21 := kw_anchor.Invoke1(v2)
							if lang.IsTruthy(tmp21) {
								tmp22 := kw_anchor.Invoke1(v2)
								var tmp23 any = v19
								tmp23 = lang.Assoc(tmp23, kw_anchor, tmp22)
								tmp20 = tmp23
							} else {
								tmp20 = v19
							}
							var v24 any = tmp20
							_ = v24
							// let binding "G__3"
							var tmp25 any
							tmp26 := kw_tag.Invoke1(v2)
							if lang.IsTruthy(tmp26) {
								tmp27 := kw_tag.Invoke1(v2)
								var tmp28 any = v24
								tmp28 = lang.Assoc(tmp28, kw_tag, tmp27)
								tmp25 = tmp28
							} else {
								tmp25 = v24
							}
							var v29 any = tmp25
							_ = v29
							var tmp30 any
							tmp31 := kw_flow.Invoke1(v2)
							if lang.IsTruthy(tmp31) {
								tmp32 := kw_flow.Invoke1(v2)
								var tmp33 any = v29
								tmp33 = lang.Assoc(tmp33, kw_flow, tmp32)
								tmp30 = tmp33
							} else {
								tmp30 = v29
							}
							tmp17 = tmp30
						} // end let
						tmp18 := lang.NewVector(tmp17)
						var tmp19 lang.FnFunc1
						tmp19 = lang.FnFunc1(func(p0 any) any {
							v20 := p0
							_ = v20
							var tmp21 any
							{ // let
								// let binding "vec__5"
								var v22 any = v20
								_ = v22
								// let binding "k"
								tmp23 := runtime.RT.NthDefault(v22, lang.IntCast(int64(0)), nil)
								var v24 any = tmp23
								_ = v24
								// let binding "v"
								tmp25 := runtime.RT.NthDefault(v22, lang.IntCast(int64(1)), nil)
								var v26 any = tmp25
								_ = v26
								tmp27 := aotDirectFn2(v24)
								tmp28 := aotDirectFn2(v26)
								tmp29 := aotExternalFn5(tmp27, tmp28)
								tmp21 = tmp29
							} // end let
							return tmp21
						})
						tmp20 := kw_value.Invoke1(v2)
						tmp21 := aotExternalFn2(tmp19, tmp20)
						tmp22 := lang.NewMap(kw_event, "mapping_end")
						tmp23 := lang.NewVector(tmp22)
						tmp24 := aotExternalFn1(tmp18, tmp21, tmp23)
						tmp25 := aotExternalFn0(tmp24)
						tmp6 = tmp25
					} else {
						tmp26 := aotExternalFn3("No matching clause: ", v5)
						tmp27 := lang.Apply1(lang.NewIllegalArgumentError, tmp26)
						panic(tmp27)
					}
					// case entry 3 (key=3, collision=false)
				} else if tmp7 == 3 {
					if v5 == kw_sequence {
						var tmp28 any
						{ // let
							// let binding "G__8"
							tmp29 := lang.NewMap(kw_event, "sequence_start")
							var v30 any = tmp29
							_ = v30
							// let binding "G__8"
							var tmp31 any
							tmp32 := kw_anchor.Invoke1(v2)
							if lang.IsTruthy(tmp32) {
								tmp33 := kw_anchor.Invoke1(v2)
								var tmp34 any = v30
								tmp34 = lang.Assoc(tmp34, kw_anchor, tmp33)
								tmp31 = tmp34
							} else {
								tmp31 = v30
							}
							var v35 any = tmp31
							_ = v35
							// let binding "G__8"
							var tmp36 any
							tmp37 := kw_tag.Invoke1(v2)
							if lang.IsTruthy(tmp37) {
								tmp38 := kw_tag.Invoke1(v2)
								var tmp39 any = v35
								tmp39 = lang.Assoc(tmp39, kw_tag, tmp38)
								tmp36 = tmp39
							} else {
								tmp36 = v35
							}
							var v40 any = tmp36
							_ = v40
							var tmp41 any
							tmp42 := kw_flow.Invoke1(v2)
							if lang.IsTruthy(tmp42) {
								tmp43 := kw_flow.Invoke1(v2)
								var tmp44 any = v40
								tmp44 = lang.Assoc(tmp44, kw_flow, tmp43)
								tmp41 = tmp44
							} else {
								tmp41 = v40
							}
							tmp28 = tmp41
						} // end let
						tmp29 := lang.NewVector(tmp28)
						tmp30 := checkDerefVar(var_yamlstar_DOT_serializer_serialize_DASH_node)
						tmp31 := kw_value.Invoke1(v2)
						tmp32 := aotExternalFn2(tmp30, tmp31)
						tmp33 := lang.NewMap(kw_event, "sequence_end")
						tmp34 := lang.NewVector(tmp33)
						tmp35 := aotExternalFn1(tmp29, tmp32, tmp34)
						tmp36 := aotExternalFn0(tmp35)
						tmp6 = tmp36
					} else {
						tmp37 := aotExternalFn3("No matching clause: ", v5)
						tmp38 := lang.Apply1(lang.NewIllegalArgumentError, tmp37)
						panic(tmp38)
					}
				} else {
					tmp39 := aotExternalFn3("No matching clause: ", v5)
					tmp40 := lang.Apply1(lang.NewIllegalArgumentError, tmp39)
					panic(tmp40)
				}
				tmp3 = tmp6
			} // end let
			return tmp3
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_serializer_serialize_DASH_node = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_serializer_serialize_DASH_node.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/serializer.glj", kw_line, int(5), kw_column, int(8), kw_end_DASH_line, int(5), kw_end_DASH_column, int(21), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_node)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_serializer))
		})
	}
}
