FROM fedora:rawhide

RUN dnf -y --setopt=install_weak_deps=False install \
      bzip2 \
      findutils \
      git-core \
      go-rpm-macros \
      go-vendor-tools \
      golang \
      gzip \
      redhat-rpm-config \
      rpm-build \
      rpmautospec \
      rpmlint \
      tar \
    && dnf clean all

RUN dnf -y --setopt=install_weak_deps=False install askalono-cli \
    && dnf clean all

WORKDIR /build
