// Code generated by glojure codegen. DO NOT EDIT.

package parser

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
)

var aotDirectFn0 lang.FnFunc0
var aotDirectFn1 lang.FnFunc1
var aotDirectFn2 lang.FnFunc0
var aotDirectFn3 lang.FnFunc0

func init() {
	runtime.RegisterNSLoader("yamlstar/plugin/parser", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.plugin.parser"
func LoadNS() {
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_go_DASH_yaml := lang.NewSymbolUnchecked("go-yaml")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_parser_DASH_name := lang.NewSymbolUnchecked("parser-name")
	sym_reference := lang.NewSymbolUnchecked("reference")
	sym_snakeyaml := lang.NewSymbolUnchecked("snakeyaml")
	sym_yamlstar_DOT_plugin_DOT_parser := lang.NewSymbolUnchecked("yamlstar.plugin.parser")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_line := lang.NewKeyword("line")
	kw_name := lang.NewKeyword("name")
	kw_ns := lang.NewKeyword("ns")
	kw_parser := lang.NewKeyword("parser")
	// var yamlstar.plugin.parser/go-yaml
	var_yamlstar_DOT_plugin_DOT_parser_go_DASH_yaml := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_parser, sym_go_DASH_yaml)
	// var yamlstar.plugin.parser/name
	var_yamlstar_DOT_plugin_DOT_parser_name := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_parser, sym_name)
	// var yamlstar.plugin.parser/reference
	var_yamlstar_DOT_plugin_DOT_parser_reference := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_parser, sym_reference)
	// var yamlstar.plugin.parser/snakeyaml
	var_yamlstar_DOT_plugin_DOT_parser_snakeyaml := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_parser, sym_snakeyaml)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_parser)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"name",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// go-yaml
	{
		tmp0 := sym_go_DASH_yaml
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn1("go-yaml")
			return tmp2
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_plugin_DOT_parser_go_DASH_yaml = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_parser_go_DASH_yaml.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/parser.glj", kw_line, int(19), kw_column, int(7), kw_end_DASH_line, int(19), kw_end_DASH_column, int(13), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Select the go-yaml parser plugin.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_parser))
		})
	}
	// name
	{
		tmp0 := sym_name
		var tmp1 lang.FnFunc1
		tmp1 = lang.FnFunc1(func(p0 any) any {
			v2 := p0
			_ = v2
			tmp3 := lang.NewMap(kw_name, v2)
			tmp4 := lang.NewMap(kw_parser, tmp3)
			return tmp4
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_plugin_DOT_parser_name = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_parser_name.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/parser.glj", kw_line, int(4), kw_column, int(7), kw_end_DASH_line, int(4), kw_end_DASH_column, int(10), kw_arglists, lang.NewList(lang.NewVector(sym_parser_DASH_name)), kw_doc, "Select a parser plugin by name.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_parser))
		})
	}
	// reference
	{
		tmp0 := sym_reference
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn1("reference")
			return tmp2
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_plugin_DOT_parser_reference = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_parser_reference.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/parser.glj", kw_line, int(9), kw_column, int(7), kw_end_DASH_line, int(9), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Select the built-in reference parser plugin.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_parser))
		})
	}
	// snakeyaml
	{
		tmp0 := sym_snakeyaml
		var tmp1 lang.FnFunc0
		tmp1 = lang.FnFunc0(func() any {
			tmp2 := aotDirectFn1("snakeyaml")
			return tmp2
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_plugin_DOT_parser_snakeyaml = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_parser_snakeyaml.SetMetaLazy(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/parser.glj", kw_line, int(14), kw_column, int(7), kw_end_DASH_line, int(14), kw_end_DASH_column, int(15), kw_arglists, lang.NewList(lang.NewVector()), kw_doc, "Select the SnakeYAML parser plugin.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_parser))
		})
	}
}
