// Code generated by glojure codegen. DO NOT EDIT.

package shared

import (
	fmt "fmt"
	lang "github.com/glojurelang/glojure/pkg/lang"
	runtime "github.com/glojurelang/glojure/pkg/runtime"
	reflect "reflect"
	atomic "sync/atomic"
)

var aotDirectFn0 lang.FnFunc2
var aotDirectFn1 lang.FnFunc2
var aotDirectFn2 lang.FnFunc3
var aotDirectFn3 lang.FnFunc3

var aotKeywordMapShape0 = lang.NewKeywordMapShape("api", "name")

type aotKeywordMapStorage0 struct {
	lang.Map
	values [2]any
}

func aotKeywordMapNew0(v0 any, v1 any) *lang.Map {
	storage := &aotKeywordMapStorage0{}
	storage.values = [2]any{v0, v1}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape0,
		storage.values[:],
	)
}

var aotKeywordSite0 lang.KeywordSite
var aotKeywordMapShape1 = lang.NewKeywordMapShape("api", "name", "kind")

type aotKeywordMapStorage1 struct {
	lang.Map
	values [3]any
}

func aotKeywordMapNew1(v0 any, v1 any, v2 any) *lang.Map {
	storage := &aotKeywordMapStorage1{}
	storage.values = [3]any{v0, v1, v2}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape1,
		storage.values[:],
	)
}

var aotKeywordMapShape2 = lang.NewKeywordMapShape("api", "name", "status", "response")

type aotKeywordMapStorage2 struct {
	lang.Map
	values [4]any
}

func aotKeywordMapNew2(v0 any, v1 any, v2 any, v3 any) *lang.Map {
	storage := &aotKeywordMapStorage2{}
	storage.values = [4]any{v0, v1, v2, v3}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape2,
		storage.values[:],
	)
}

var aotKeywordMapShape3 = lang.NewKeywordMapShape("api", "name", "version", "manifest", "default-config", "sanitize")

type aotKeywordMapStorage3 struct {
	lang.Map
	values [6]any
}

func aotKeywordMapNew3(v0 any, v1 any, v2 any, v3 any, v4 any, v5 any) *lang.Map {
	storage := &aotKeywordMapStorage3{}
	storage.values = [6]any{v0, v1, v2, v3, v4, v5}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape3,
		storage.values[:],
	)
}

var aotKeywordMapShape4 = lang.NewKeywordMapShape("context", "text")

type aotKeywordMapStorage4 struct {
	lang.Map
	values [2]any
}

func aotKeywordMapNew4(v0 any, v1 any) *lang.Map {
	storage := &aotKeywordMapStorage4{}
	storage.values = [2]any{v0, v1}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape4,
		storage.values[:],
	)
}

var aotKeywordMapShape5 = lang.NewKeywordMapShape("key", "expected", "actual")

type aotKeywordMapStorage5 struct {
	lang.Map
	values [3]any
}

func aotKeywordMapNew5(v0 any, v1 any, v2 any) *lang.Map {
	storage := &aotKeywordMapStorage5{}
	storage.values = [3]any{v0, v1, v2}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape5,
		storage.values[:],
	)
}

var aotKeywordMapShape6 = lang.NewKeywordMapShape("manifest")

type aotKeywordMapStorage6 struct {
	lang.Map
	values [1]any
}

func aotKeywordMapNew6(v0 any) *lang.Map {
	storage := &aotKeywordMapStorage6{}
	storage.values = [1]any{v0}
	return lang.InitStaticKeywordMap(
		&storage.Map,
		aotKeywordMapShape6,
		storage.values[:],
	)
}
func aotLinkFn1(vr *lang.Var) lang.FnFunc1 {
	if vr.IsBound() {
		return aotLinkBoundFn1(vr)
	}
	var linked atomic.Pointer[lang.FnFunc1]
	return func(p0 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0)
		}
		if !vr.IsBound() {
			return lang.Apply1(checkDerefVar(vr), p0)
		}
		fn := aotLinkBoundFn1(vr)
		linked.Store(&fn)
		return fn(p0)
	}
}

func aotLinkBoundFn1(vr *lang.Var) lang.FnFunc1 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn1(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn1); ok {
		return fixed.Invoke1
	}
	return func(p0 any) any { return lang.Apply1(fn, p0) }
}

func aotLinkFn2(vr *lang.Var) lang.FnFunc2 {
	if vr.IsBound() {
		return aotLinkBoundFn2(vr)
	}
	var linked atomic.Pointer[lang.FnFunc2]
	return func(p0 any, p1 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1)
		}
		if !vr.IsBound() {
			return lang.Apply2(checkDerefVar(vr), p0, p1)
		}
		fn := aotLinkBoundFn2(vr)
		linked.Store(&fn)
		return fn(p0, p1)
	}
}

func aotLinkBoundFn2(vr *lang.Var) lang.FnFunc2 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn2(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn2); ok {
		return fixed.Invoke2
	}
	return func(p0 any, p1 any) any { return lang.Apply2(fn, p0, p1) }
}

func aotLinkFn3(vr *lang.Var) lang.FnFunc3 {
	if vr.IsBound() {
		return aotLinkBoundFn3(vr)
	}
	var linked atomic.Pointer[lang.FnFunc3]
	return func(p0 any, p1 any, p2 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2)
		}
		if !vr.IsBound() {
			return lang.Apply3(checkDerefVar(vr), p0, p1, p2)
		}
		fn := aotLinkBoundFn3(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2)
	}
}

func aotLinkBoundFn3(vr *lang.Var) lang.FnFunc3 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn3(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn3); ok {
		return fixed.Invoke3
	}
	return func(p0 any, p1 any, p2 any) any { return lang.Apply3(fn, p0, p1, p2) }
}

func aotLinkFn4(vr *lang.Var) lang.FnFunc4 {
	if vr.IsBound() {
		return aotLinkBoundFn4(vr)
	}
	var linked atomic.Pointer[lang.FnFunc4]
	return func(p0 any, p1 any, p2 any, p3 any) any {
		if fn := linked.Load(); fn != nil {
			return (*fn)(p0, p1, p2, p3)
		}
		if !vr.IsBound() {
			return lang.Apply4(checkDerefVar(vr), p0, p1, p2, p3)
		}
		fn := aotLinkBoundFn4(vr)
		linked.Store(&fn)
		return fn(p0, p1, p2, p3)
	}
}

func aotLinkBoundFn4(vr *lang.Var) lang.FnFunc4 {
	fn := checkDerefVar(vr)
	if direct, ok := lang.DirectFn4(fn); ok {
		return direct
	}
	if fixed, ok := fn.(lang.FixedArityFn4); ok {
		return fixed.Invoke4
	}
	return func(p0 any, p1 any, p2 any, p3 any) any { return lang.Apply4(fn, p0, p1, p2, p3) }
}

func init() {
	runtime.RegisterNSLoader("yamlstar/plugin/shared", LoadNS)
}

func checkDerefVar(v *lang.Var) any {
	if v.IsMacro() {
		panic(lang.NewIllegalArgumentError(fmt.Sprintf("can't take value of macro: %v", v)))
	}
	return v.Get()
}

func checkArity(args []any, expected int) {
	if len(args) != expected {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

func checkArityGTE(args []any, min int) {
	if len(args) < min {
		panic(lang.NewIllegalArgumentError("wrong number of arguments (" + fmt.Sprint(len(args)) + ")"))
	}
}

// LoadNS initializes the namespace "yamlstar.plugin.shared"
func LoadNS() {
	sym_abi_DASH_version := lang.NewSymbolUnchecked("abi-version")
	sym_api := lang.NewSymbolUnchecked("api")
	sym_clojure_DOT_core := lang.NewSymbolUnchecked("clojure.core")
	sym_context := lang.NewSymbolUnchecked("context")
	sym_ex_DASH_info := lang.NewSymbolUnchecked("ex-info")
	sym_expected := lang.NewSymbolUnchecked("expected")
	sym_key := lang.NewSymbolUnchecked("key")
	sym_make_DASH_loader := lang.NewSymbolUnchecked("make-loader")
	sym_manifest := lang.NewSymbolUnchecked("manifest")
	sym_manifest_DASH_fn := lang.NewSymbolUnchecked("manifest-fn")
	sym_name := lang.NewSymbolUnchecked("name")
	sym_pr_DASH_str := lang.NewSymbolUnchecked("pr-str")
	sym_read_DASH_edn := lang.NewSymbolUnchecked("read-edn")
	sym_read_DASH_string := lang.NewSymbolUnchecked("read-string")
	sym_require_DASH_value := lang.NewSymbolUnchecked("require-value")
	sym_str := lang.NewSymbolUnchecked("str")
	sym_text := lang.NewSymbolUnchecked("text")
	sym_transform_DASH_fn := lang.NewSymbolUnchecked("transform-fn")
	sym_validate_DASH_manifest := lang.NewSymbolUnchecked("validate-manifest")
	sym_yamlstar_DOT_plugin_DOT_shared := lang.NewSymbolUnchecked("yamlstar.plugin.shared")
	kw_abi := lang.NewKeyword("abi")
	kw_api := lang.NewKeyword("api")
	kw_arglists := lang.NewKeyword("arglists")
	kw_column := lang.NewKeyword("column")
	kw_doc := lang.NewKeyword("doc")
	kw_end_DASH_column := lang.NewKeyword("end-column")
	kw_end_DASH_line := lang.NewKeyword("end-line")
	kw_file := lang.NewKeyword("file")
	kw_kind := lang.NewKeyword("kind")
	kw_line := lang.NewKeyword("line")
	kw_name := lang.NewKeyword("name")
	kw_ns := lang.NewKeyword("ns")
	kw_private := lang.NewKeyword("private")
	kw_transform := lang.NewKeyword("transform")
	kw_version := lang.NewKeyword("version")
	builtin_any := lang.Builtins["any"]
	// var clojure.core/ex-info
	var_clojure_DOT_core_ex_DASH_info := lang.InternVarName(sym_clojure_DOT_core, sym_ex_DASH_info)
	// var clojure.core/name
	var_clojure_DOT_core_name := lang.InternVarName(sym_clojure_DOT_core, sym_name)
	// var clojure.core/pr-str
	var_clojure_DOT_core_pr_DASH_str := lang.InternVarName(sym_clojure_DOT_core, sym_pr_DASH_str)
	// var clojure.core/read-string
	var_clojure_DOT_core_read_DASH_string := lang.InternVarName(sym_clojure_DOT_core, sym_read_DASH_string)
	// var clojure.core/str
	var_clojure_DOT_core_str := lang.InternVarName(sym_clojure_DOT_core, sym_str)
	// var yamlstar.plugin.shared/abi-version
	var_yamlstar_DOT_plugin_DOT_shared_abi_DASH_version := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_abi_DASH_version)
	// var yamlstar.plugin.shared/make-loader
	var_yamlstar_DOT_plugin_DOT_shared_make_DASH_loader := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_make_DASH_loader)
	// var yamlstar.plugin.shared/read-edn
	var_yamlstar_DOT_plugin_DOT_shared_read_DASH_edn := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_read_DASH_edn)
	// var yamlstar.plugin.shared/require-value
	var_yamlstar_DOT_plugin_DOT_shared_require_DASH_value := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_require_DASH_value)
	// var yamlstar.plugin.shared/validate-manifest
	var_yamlstar_DOT_plugin_DOT_shared_validate_DASH_manifest := lang.InternVarName(sym_yamlstar_DOT_plugin_DOT_shared, sym_validate_DASH_manifest)
	aotExternalFn1 := aotLinkFn2(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn2 := aotLinkFn1(var_clojure_DOT_core_pr_DASH_str)
	aotExternalFn5 := aotLinkFn3(var_clojure_DOT_core_ex_DASH_info)
	aotExternalFn6 := aotLinkFn2(var_clojure_DOT_core_str)
	aotExternalFn7 := aotLinkFn1(var_clojure_DOT_core_read_DASH_string)
	aotExternalFn8 := aotLinkFn4(var_clojure_DOT_core_str)
	aotExternalFn9 := aotLinkFn1(var_clojure_DOT_core_name)
	// reference fmt to avoid unused import error
	_ = fmt.Printf
	// reference reflect to avoid unused import error
	_ = reflect.TypeOf
	ns := lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared)
	_ = ns
	{ // refer vars from clojure.core
		srcNS := lang.FindOrCreateNamespace(sym_clojure_DOT_core)
		ns.ReferAllSnapshot(srcNS, []string{
			"*loaded-libs*",
			"*loading-verbosely*",
			"*pending-paths*",
			"-protocols",
			">0?",
			">1?",
			"add-doc-and-meta",
			"array",
			"assert-args",
			"assert-valid-fdecl",
			"binding-conveyor-fn",
			"case-map",
			"check-cyclic-dependency",
			"check-valid-options",
			"data-reader-urls",
			"data-reader-var",
			"def-aset",
			"deref-as-map",
			"deref-future",
			"elide-top-frames",
			"emit-extend-protocol",
			"emit-extend-type",
			"emit-hinted-impl",
			"filter-key",
			"fits-table?",
			"global-hierarchy",
			"into1",
			"libspec?",
			"lift-ns",
			"load-all",
			"load-data-reader-file",
			"load-data-readers",
			"load-lib",
			"load-libs",
			"load-one",
			"max-mask-bits",
			"max-switch-table-size",
			"maybe-destructured",
			"maybe-min-hash",
			"merge-hash-collisions",
			"mk-bound-fn",
			"nary-inline",
			"normalize-slurp-opts",
			"parse-impls",
			"parsing-err",
			"pr-on",
			"prep-hashes",
			"prep-ints",
			"prependss",
			"preserving-reduced",
			"print-initialized",
			"print-map",
			"print-meta",
			"print-object",
			"print-prefix-map",
			"print-sequential",
			"print-tagged-object",
			"print-throwable",
			"protocol?",
			"reduce1",
			"root-directory",
			"root-resource",
			"serialized-require",
			"setup-reference",
			"shift-mask",
			"sigs",
			"spread",
			"strip-ns",
			"system-newline",
			"tapset",
			"throw-if",
		})
	}
	// abi-version
	{
		tmp0 := sym_abi_DASH_version
		var_yamlstar_DOT_plugin_DOT_shared_abi_DASH_version = ns.InternWithValue(tmp0, int64(2), true)
		var_yamlstar_DOT_plugin_DOT_shared_abi_DASH_version.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMap(kw_file, "yamlstar/plugin/shared.glj", kw_line, int(4), kw_column, int(6), kw_end_DASH_line, int(4), kw_end_DASH_column, int(16), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
		}, false)
	}
	// make-loader
	{
		tmp0 := sym_make_DASH_loader
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 lang.FnFunc4
			tmp4 = lang.FnFunc4(func(p0, p1, p2, p3 any) any {
				v5 := p0
				_ = v5
				v6 := p1
				_ = v6
				v7 := p2
				_ = v7
				v8 := p3
				_ = v8
				var tmp9 any
				var tmp10 any
				{ // let
					// let binding "and__0__auto__"
					tmp11 := lang.Equals(v5, "json-comments")
					var v12 any = tmp11
					_ = v12
					var tmp13 any
					if lang.IsTruthy(v12) {
						tmp14 := lang.Equals(v6, "sanitizer")
						tmp13 = tmp14
					} else {
						tmp13 = v12
					}
					tmp10 = tmp13
				} // end let
				if lang.IsTruthy(tmp10) {
				} else {
					tmp11 := aotKeywordMapNew0(v5, v6)
					tmp12 := aotExternalFn1("No shared plugin artifact for implementation", tmp11)
					panic(tmp12)
				}
				_ = tmp9
				var tmp13 any
				{ // let
					// let binding "artifact"
					var v14 any = "json-comments"
					_ = v14
					// let binding "manifest"
					tmp15 := lang.Apply3(v2, v5, v14, v8)
					tmp16 := aotDirectFn1(tmp15, "manifest")
					tmp17 := aotDirectFn3(tmp16, v5, v6)
					var v18 any = tmp17
					_ = v18
					tmp19 := aotKeywordSite0.Get(kw_version, v18, nil)
					tmp20 := lang.NewMap()
					var tmp21 lang.FnFunc2
					tmp21 = lang.FnFunc2(func(p0, p1 any) any {
						v22 := p0
						_ = v22
						v23 := p1
						_ = v23
						var tmp24 any
						{ // let
							// let binding "vec__19"
							var tmp25 any
							{ // let
								// let binding "or__0__auto__"
								var v26 any = v22
								_ = v26
								var tmp27 any
								if lang.IsTruthy(v26) {
									tmp27 = v26
								} else {
									tmp27 = ""
								}
								tmp25 = tmp27
							} // end let
							tmp26 := aotExternalFn2(v23)
							tmp27 := lang.Apply4(v3, v5, v14, tmp25, tmp26)
							var v28 any = tmp27
							_ = v28
							// let binding "status"
							tmp29 := runtime.RT.NthDefault(v28, lang.IntCast(int64(0)), nil)
							var v30 any = tmp29
							_ = v30
							// let binding "output"
							tmp31 := runtime.RT.NthDefault(v28, lang.IntCast(int64(1)), nil)
							var v32 any = tmp31
							_ = v32
							var tmp33 any
							{ // let
								// let binding "G__22"
								tmp34 := lang.LongCastBoxed(v30)
								var v35 any = tmp34
								_ = v35
								// case
								var tmp36 any
								var tmp37 int64
								switch v := v35.(type) {
								case int64:
									tmp37 = v
								case int:
									tmp37 = int64(v)
								case int32:
									tmp37 = int64(v)
								case int16:
									tmp37 = int64(v)
								case int8:
									tmp37 = int64(v)
								default:
									tmp37 = -1 // won't match any case
								}
								// case entry 0 (key=0, collision=false)
								if tmp37 == 0 {
									tmp36 = v32
									// case entry 1 (key=1, collision=false)
								} else if tmp37 == 1 {
									tmp38 := aotKeywordMapNew1(v5, v6, kw_transform)
									tmp39 := aotExternalFn1(v32, tmp38)
									panic(tmp39)
								} else {
									tmp40 := aotKeywordMapNew2(v5, v6, v30, v32)
									tmp41 := aotExternalFn1("Shared plugin ABI call failed", tmp40)
									panic(tmp41)
								}
								tmp33 = tmp36
							} // end let
							tmp24 = tmp33
						} // end let
						return tmp24
					})
					tmp22 := aotKeywordMapNew3(v5, v6, tmp19, v18, tmp20, tmp21)
					tmp13 = tmp22
				} // end let
				return tmp13
			})
			return tmp4
		})
		aotDirectFn0 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_make_DASH_loader = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_make_DASH_loader.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared.glj", kw_line, int(35), kw_column, int(7), kw_end_DASH_line, int(35), kw_end_DASH_column, int(17), kw_arglists, lang.NewList(lang.NewVector(sym_manifest_DASH_fn, sym_transform_DASH_fn)), kw_doc, "Create a JSON-comments loader from native host functions.\n\n  manifest-fn receives api, artifact name, and install? and returns EDN.\n  transform-fn receives api, artifact name, input, and options EDN and\n  returns [status output].", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
		}, false)
	}
	// read-edn
	{
		tmp0 := sym_read_DASH_edn
		var tmp1 lang.FnFunc2
		tmp1 = lang.FnFunc2(func(p0, p1 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			var tmp4 any
			func() {
				defer func() {
					if r := recover(); r != nil {
						if lang.CatchMatches(r, builtin_any) {
							v5 := r
							_ = v5
							tmp6 := aotExternalFn6("Invalid EDN from shared plugin ", v3)
							tmp7 := aotKeywordMapNew4(v3, v2)
							tmp8 := aotExternalFn5(tmp6, tmp7, v5)
							panic(tmp8)
						} else {
							panic(r)
						}
					}
				}()
				tmp5 := aotExternalFn7(v2)
				tmp4 = tmp5
			}()
			return tmp4
		})
		aotDirectFn1 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_read_DASH_edn = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_read_DASH_edn.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared.glj", kw_line, int(6), kw_column, int(8), kw_end_DASH_line, int(6), kw_end_DASH_column, int(15), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_text, sym_context)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
		}, false)
	}
	// require-value
	{
		tmp0 := sym_require_DASH_value
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			tmp6 := runtime.RT.Get(v2, v3)
			tmp7 := lang.Equals(v4, tmp6)
			if tmp7 {
			} else {
				tmp8 := aotExternalFn9(v3)
				tmp9 := aotExternalFn2(v4)
				tmp10 := aotExternalFn8("Shared plugin manifest ", tmp8, " must be ", tmp9)
				tmp11 := runtime.RT.Get(v2, v3)
				tmp12 := aotKeywordMapNew5(v3, v4, tmp11)
				tmp13 := aotExternalFn1(tmp10, tmp12)
				panic(tmp13)
			}
			return tmp5
		})
		aotDirectFn2 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_require_DASH_value = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_require_DASH_value.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared.glj", kw_line, int(15), kw_column, int(8), kw_end_DASH_line, int(15), kw_end_DASH_column, int(20), kw_private, true, kw_arglists, lang.NewList(lang.NewVector(sym_manifest, sym_key, sym_expected)), kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
		}, false)
	}
	// validate-manifest
	{
		tmp0 := sym_validate_DASH_manifest
		var tmp1 lang.FnFunc3
		tmp1 = lang.FnFunc3(func(p0, p1, p2 any) any {
			v2 := p0
			_ = v2
			v3 := p1
			_ = v3
			v4 := p2
			_ = v4
			var tmp5 any
			tmp6 := lang.IsMap(v2)
			if tmp6 {
			} else {
				tmp7 := aotKeywordMapNew6(v2)
				tmp8 := aotExternalFn1("Shared plugin manifest must be an EDN map", tmp7)
				panic(tmp8)
			}
			_ = tmp5
			tmp9 := checkDerefVar(var_yamlstar_DOT_plugin_DOT_shared_abi_DASH_version)
			tmp10 := aotDirectFn2(v2, kw_abi, tmp9)
			_ = tmp10
			tmp11 := aotDirectFn2(v2, kw_api, v3)
			_ = tmp11
			tmp12 := aotDirectFn2(v2, kw_name, v4)
			_ = tmp12
			tmp13 := aotDirectFn2(v2, kw_kind, "text-transform")
			_ = tmp13
			return v2
		})
		aotDirectFn3 = tmp1
		var_yamlstar_DOT_plugin_DOT_shared_validate_DASH_manifest = ns.InternWithValue(tmp0, tmp1, true)
		var_yamlstar_DOT_plugin_DOT_shared_validate_DASH_manifest.SetMetaLazyMacro(func() lang.IPersistentMap {
			return lang.NewMapUniqueKeys(kw_file, "yamlstar/plugin/shared.glj", kw_line, int(23), kw_column, int(7), kw_end_DASH_line, int(23), kw_end_DASH_column, int(23), kw_arglists, lang.NewList(lang.NewVector(sym_manifest, sym_api, sym_name)), kw_doc, "Validate a shared plugin manifest for the requested API and name.", kw_ns, lang.FindOrCreateNamespace(sym_yamlstar_DOT_plugin_DOT_shared))
		}, false)
	}
}
